/*
 * This file was generated by qdbusxml2cpp version 0.7
 * Command line was: qdbusxml2cpp -v -c CvMsdxClientServiceIf -p CvMsdxClientServiceIf.h:CvMsdxClientServiceIf.cpp .\com.coolview.cvmsdxclient.xml
 *
 * qdbusxml2cpp is Copyright (C) 2010 Nokia Corporation and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#ifndef CVMSDXCLIENTSERVICEIF_H_1285575475
#define CVMSDXCLIENTSERVICEIF_H_1285575475

#include <QtCore/QObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>
#include <QtDBus/QtDBus>

/*
 * Proxy class for interface com.coolview.cvmsdxclient
 */
class CvMsdxClientServiceIf: public QDBusAbstractInterface
{
    Q_OBJECT
public:
    static inline const char *staticInterfaceName()
    { return "com.coolview.cvmsdxclient"; }

public:
    CvMsdxClientServiceIf(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent = 0);

    ~CvMsdxClientServiceIf();

public Q_SLOTS: // METHODS
    inline QDBusReply<int> client_request(int action_id, const QByteArray &input_garray)
    {
        QList<QVariant> argumentList;
        argumentList << qVariantFromValue(action_id) << qVariantFromValue(input_garray);
		return callWithArgumentList(QDBus::NoBlock , QLatin1String("client_request"), argumentList);
    }

Q_SIGNALS: // SIGNALS
};

namespace com {
  namespace coolview {
    typedef ::CvMsdxClientServiceIf cvmsdxclient;
  }
}
#endif
