/*
 * This file was generated by qdbusxml2cpp version 0.7
 * Command line was: qdbusxml2cpp -c CvConfigAdaptor -a CvConfigAdaptor.h:CvConfigAdaptor.cpp .\com.dcampus.coolview.configuration.xml
 *
 * qdbusxml2cpp is Copyright (C) 2010 Nokia Corporation and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include "CvConfigAdaptor.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Implementation of adaptor class CvConfigAdaptor
 */

CvConfigAdaptor::CvConfigAdaptor(QObject *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

CvConfigAdaptor::~CvConfigAdaptor()
{
    // destructor
}

void CvConfigAdaptor::QueryAllConfig(int subscribe_id)
{
    // handle method call com.dcampus.coolview.configuration.QueryAllConfig
    QMetaObject::invokeMethod(parent(), "QueryAllConfig", Q_ARG(int, subscribe_id));
}

void CvConfigAdaptor::QueryCurrentConfig(int subscribe_id)
{
    // handle method call com.dcampus.coolview.configuration.QueryCurrentConfig
    QMetaObject::invokeMethod(parent(), "QueryCurrentConfig", Q_ARG(int, subscribe_id));
}

void CvConfigAdaptor::RefreshConfig()
{
    // handle method call com.dcampus.coolview.configuration.RefreshConfig
    QMetaObject::invokeMethod(parent(), "RefreshConfig");
}

void CvConfigAdaptor::SetCamera(const QString &camera_name, const QString &crossbar_name, const QString &crossbar_type, int video_width, int video_height)
{
    // handle method call com.dcampus.coolview.configuration.SetCamera
    QMetaObject::invokeMethod(parent(), "SetCamera", Q_ARG(QString, camera_name), Q_ARG(QString, crossbar_name), Q_ARG(QString, crossbar_type), Q_ARG(int, video_width), Q_ARG(int, video_height));
}

void CvConfigAdaptor::SetIP(const QString &ip)
{
    // handle method call com.dcampus.coolview.configuration.SetIP
    QMetaObject::invokeMethod(parent(), "SetIP", Q_ARG(QString, ip));
}

void CvConfigAdaptor::SetMic(const QString &mic_name, int mic_volumn)
{
    // handle method call com.dcampus.coolview.configuration.SetMic
    QMetaObject::invokeMethod(parent(), "SetMic", Q_ARG(QString, mic_name), Q_ARG(int, mic_volumn));
}

void CvConfigAdaptor::SetSpeaker(const QString &speaker_name, int speaker_volumn)
{
    // handle method call com.dcampus.coolview.configuration.SetSpeaker
    QMetaObject::invokeMethod(parent(), "SetSpeaker", Q_ARG(QString, speaker_name), Q_ARG(int, speaker_volumn));
}

