/*
 * This file was generated by qdbusxml2cpp version 0.7
 * Command line was: qdbusxml2cpp -c CvConfigAdaptor -a CvConfigAdaptor.h:CvConfigAdaptor.cpp .\com.dcampus.coolview.configuration.xml
 *
 * qdbusxml2cpp is Copyright (C) 2010 Nokia Corporation and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef CVCONFIGADAPTOR_H_1339123379
#define CVCONFIGADAPTOR_H_1339123379

#include <QtCore/QObject>
#include <QtDBus/QtDBus>
class QByteArray;
template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;
class QStringList;
class QVariant;

/*
 * Adaptor class for interface com.dcampus.coolview.configuration
 */
class CvConfigAdaptor: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "com.dcampus.coolview.configuration")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"com.dcampus.coolview.configuration\">\n"
"    <method name=\"RefreshConfig\">\n"
"      <!--Refresh the terminal configuration -->\n"
"    </method>\n"
"    <method name=\"QueryAllConfig\">\n"
"      <!--get all configuration -->\n"
"      <arg direction=\"in\" type=\"i\" name=\"subscribe_id\"/>\n"
"      <!--subscribe_id for controller-->\n"
"    </method>\n"
"    <method name=\"QueryCurrentConfig\">\n"
"      <!--get current configuration for terminal-->\n"
"      <arg direction=\"in\" type=\"i\" name=\"subscribe_id\"/>\n"
"    </method>\n"
"    <method name=\"SetCamera\">\n"
"      <arg direction=\"in\" type=\"s\" name=\"camera_name\"/>\n"
"      <arg direction=\"in\" type=\"s\" name=\"crossbar_name\"/>\n"
"      <arg direction=\"in\" type=\"s\" name=\"crossbar_type\"/>\n"
"      <arg direction=\"in\" type=\"i\" name=\"video_width\"/>\n"
"      <arg direction=\"in\" type=\"i\" name=\"video_height\"/>\n"
"    </method>\n"
"    <method name=\"SetIP\">\n"
"      <arg direction=\"in\" type=\"s\" name=\"ip\"/>\n"
"    </method>\n"
"    <method name=\"SetSpeaker\">\n"
"      <arg direction=\"in\" type=\"s\" name=\"speaker_name\"/>\n"
"      <arg direction=\"in\" type=\"i\" name=\"speaker_volumn\"/>\n"
"    </method>\n"
"    <method name=\"SetMic\">\n"
"      <arg direction=\"in\" type=\"s\" name=\"mic_name\"/>\n"
"      <arg direction=\"in\" type=\"i\" name=\"mic_volumn\"/>\n"
"    </method>\n"
"  </interface>\n"
        "")
public:
    CvConfigAdaptor(QObject *parent);
    virtual ~CvConfigAdaptor();

public: // PROPERTIES
public Q_SLOTS: // METHODS
    void QueryAllConfig(int subscribe_id);
    void QueryCurrentConfig(int subscribe_id);
    void RefreshConfig();
    void SetCamera(const QString &camera_name, const QString &crossbar_name, const QString &crossbar_type, int video_width, int video_height);
    void SetIP(const QString &ip);
    void SetMic(const QString &mic_name, int mic_volumn);
    void SetSpeaker(const QString &speaker_name, int speaker_volumn);
Q_SIGNALS: // SIGNALS
};

#endif
