/*
 * This file was generated by qdbusxml2cpp version 0.7
 * Command line was: qdbusxml2cpp com.dcampus.coolview.im.jabber.xml -c CvMsgAccountAdaptor -a accountadaptor.h:accountadaptor.cpp
 *
 * qdbusxml2cpp is Copyright (C) 2010 Nokia Corporation and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef ACCOUNTADAPTOR_H_1293706615
#define ACCOUNTADAPTOR_H_1293706615

#include <QtCore/QObject>
#include <QtDBus/QtDBus>
class QByteArray;
template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;
class QStringList;
class QVariant;

/*
 * Adaptor class for interface com.dcampus.coolview.im.jabber
 */
class CvMsgAccountAdaptor: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "com.dcampus.coolview.im.jabber")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"com.dcampus.coolview.im.jabber\">\n"
"    <signal name=\"loginSuccess\">\n"
"      <arg direction=\"out\" type=\"s\" name=\"jid\"/>\n"
"    </signal>\n"
"    <signal name=\"connectionClose\"/>\n"
"    <signal name=\"messageReceived\">\n"
"      <arg direction=\"out\" type=\"s\" name=\"from\"/>\n"
"      <arg direction=\"out\" type=\"s\" name=\"to\"/>\n"
"      <arg direction=\"out\" type=\"s\" name=\"subject\"/>\n"
"      <arg direction=\"out\" type=\"s\" name=\"body\"/>\n"
"      <arg direction=\"out\" type=\"s\" name=\"time\"/>\n"
"    </signal>\n"
"    <signal name=\"accountPresenceChanged\">\n"
"      <arg direction=\"out\" type=\"s\" name=\"jid\"/>\n"
"      <arg direction=\"out\" type=\"i\" name=\"presence\"/>\n"
"    </signal>\n"
"    <signal name=\"accountError\">\n"
"      <arg direction=\"out\" type=\"i\" name=\"errCode\"/>\n"
"      <arg direction=\"out\" type=\"s\" name=\"details\"/>\n"
"    </signal>\n"
"    <signal name=\"presenceChanged\">\n"
"      <arg direction=\"out\" type=\"i\" name=\"status\"/>\n"
"    </signal>\n"
"    <signal name=\"groupChatInvited\">\n"
"      <arg direction=\"out\" type=\"s\" name=\"gc\"/>\n"
"      <arg direction=\"out\" type=\"s\" name=\"from\"/>\n"
"      <arg direction=\"out\" type=\"s\" name=\"reason\"/>\n"
"    </signal>\n"
"    <signal name=\"groupChatJoined\">\n"
"      <arg direction=\"out\" type=\"s\" name=\"j\"/>\n"
"    </signal>\n"
"    <signal name=\"groupChatLeft\">\n"
"      <arg direction=\"out\" type=\"s\" name=\"j\"/>\n"
"    </signal>\n"
"    <signal name=\"groupChatPresence\">\n"
"      <arg direction=\"out\" type=\"s\" name=\"j\"/>\n"
"      <arg direction=\"out\" type=\"i\" name=\"status\"/>\n"
"    </signal>\n"
"    <signal name=\"groupChatError\">\n"
"      <arg direction=\"out\" type=\"s\" name=\"j\"/>\n"
"      <arg direction=\"out\" type=\"i\" name=\"code\"/>\n"
"      <arg direction=\"out\" type=\"s\" name=\"detail\"/>\n"
"    </signal>\n"
"    <signal name=\"accountStateChanged\">\n"
"      <arg direction=\"out\" type=\"s\" name=\"jid\"/>\n"
"      <arg direction=\"out\" type=\"i\" name=\"state\"/>\n"
"    </signal>\n"
"    <signal name=\"subscriptionReceived\">\n"
"      <arg direction=\"out\" type=\"s\" name=\"j\"/>\n"
"      <arg direction=\"out\" type=\"s\" name=\"nick\"/>\n"
"    </signal>\n"
"    <signal name=\"subscriptionAccepted\">\n"
"      <arg direction=\"out\" type=\"s\" name=\"j\"/>\n"
"    </signal>\n"
"    <signal name=\"subscriptionDenied\">\n"
"      <arg direction=\"out\" type=\"s\" name=\"j\"/>\n"
"    </signal>\n"
"    <method name=\"initAccount\">\n"
"      <arg direction=\"out\" type=\"i\"/>\n"
"      <arg direction=\"in\" type=\"s\" name=\"j\"/>\n"
"      <arg direction=\"in\" type=\"s\" name=\"p\"/>\n"
"      <arg direction=\"in\" type=\"b\" name=\"overwrite\"/>\n"
"    </method>\n"
"    <method name=\"initAccount\">\n"
"      <arg direction=\"out\" type=\"i\"/>\n"
"      <arg direction=\"in\" type=\"s\" name=\"j\"/>\n"
"      <arg direction=\"in\" type=\"s\" name=\"p\"/>\n"
"    </method>\n"
"    <method name=\"login\">\n"
"      <arg direction=\"out\" type=\"i\"/>\n"
"      <arg direction=\"in\" type=\"i\" name=\"status\"/>\n"
"    </method>\n"
"    <method name=\"logout\"/>\n"
"    <method name=\"setPresence\">\n"
"      <arg direction=\"out\" type=\"i\"/>\n"
"      <arg direction=\"in\" type=\"i\" name=\"status\"/>\n"
"    </method>\n"
"    <method name=\"groupChatJoin\">\n"
"      <arg direction=\"out\" type=\"b\"/>\n"
"      <arg direction=\"in\" type=\"s\" name=\"host\"/>\n"
"      <arg direction=\"in\" type=\"s\" name=\"room\"/>\n"
"      <arg direction=\"in\" type=\"s\" name=\"nick\"/>\n"
"      <arg direction=\"in\" type=\"s\" name=\"password\"/>\n"
"      <arg direction=\"in\" type=\"i\" name=\"maxchars\"/>\n"
"      <arg direction=\"in\" type=\"i\" name=\"maxstanzas\"/>\n"
"      <arg direction=\"in\" type=\"i\" name=\"seconds\"/>\n"
"      <arg direction=\"in\" type=\"i\" name=\"Status\"/>\n"
"    </method>\n"
"    <method name=\"groupChatJoin\">\n"
"      <arg direction=\"out\" type=\"b\"/>\n"
"      <arg direction=\"in\" type=\"s\" name=\"host\"/>\n"
"      <arg direction=\"in\" type=\"s\" name=\"room\"/>\n"
"      <arg direction=\"in\" type=\"s\" name=\"nick\"/>\n"
"      <arg direction=\"in\" type=\"s\" name=\"password\"/>\n"
"      <arg direction=\"in\" type=\"i\" name=\"maxchars\"/>\n"
"      <arg direction=\"in\" type=\"i\" name=\"maxstanzas\"/>\n"
"      <arg direction=\"in\" type=\"i\" name=\"seconds\"/>\n"
"    </method>\n"
"    <method name=\"groupChatJoin\">\n"
"      <arg direction=\"out\" type=\"b\"/>\n"
"      <arg direction=\"in\" type=\"s\" name=\"host\"/>\n"
"      <arg direction=\"in\" type=\"s\" name=\"room\"/>\n"
"      <arg direction=\"in\" type=\"s\" name=\"nick\"/>\n"
"      <arg direction=\"in\" type=\"s\" name=\"password\"/>\n"
"      <arg direction=\"in\" type=\"i\" name=\"maxchars\"/>\n"
"      <arg direction=\"in\" type=\"i\" name=\"maxstanzas\"/>\n"
"    </method>\n"
"    <method name=\"groupChatJoin\">\n"
"      <arg direction=\"out\" type=\"b\"/>\n"
"      <arg direction=\"in\" type=\"s\" name=\"host\"/>\n"
"      <arg direction=\"in\" type=\"s\" name=\"room\"/>\n"
"      <arg direction=\"in\" type=\"s\" name=\"nick\"/>\n"
"      <arg direction=\"in\" type=\"s\" name=\"password\"/>\n"
"      <arg direction=\"in\" type=\"i\" name=\"maxchars\"/>\n"
"    </method>\n"
"    <method name=\"groupChatJoin\">\n"
"      <arg direction=\"out\" type=\"b\"/>\n"
"      <arg direction=\"in\" type=\"s\" name=\"host\"/>\n"
"      <arg direction=\"in\" type=\"s\" name=\"room\"/>\n"
"      <arg direction=\"in\" type=\"s\" name=\"nick\"/>\n"
"      <arg direction=\"in\" type=\"s\" name=\"password\"/>\n"
"    </method>\n"
"    <method name=\"groupChatJoin\">\n"
"      <arg direction=\"out\" type=\"b\"/>\n"
"      <arg direction=\"in\" type=\"s\" name=\"host\"/>\n"
"      <arg direction=\"in\" type=\"s\" name=\"room\"/>\n"
"      <arg direction=\"in\" type=\"s\" name=\"nick\"/>\n"
"    </method>\n"
"    <method name=\"groupChatSetStatus\">\n"
"      <arg direction=\"in\" type=\"s\" name=\"host\"/>\n"
"      <arg direction=\"in\" type=\"s\" name=\"room\"/>\n"
"      <arg direction=\"in\" type=\"i\" name=\"status\"/>\n"
"    </method>\n"
"    <method name=\"groupChatChangeNick\">\n"
"      <arg direction=\"in\" type=\"s\" name=\"host\"/>\n"
"      <arg direction=\"in\" type=\"s\" name=\"room\"/>\n"
"      <arg direction=\"in\" type=\"s\" name=\"nick\"/>\n"
"      <arg direction=\"in\" type=\"i\" name=\"status\"/>\n"
"    </method>\n"
"    <method name=\"groupChatLeave\">\n"
"      <arg direction=\"in\" type=\"s\" name=\"host\"/>\n"
"      <arg direction=\"in\" type=\"s\" name=\"room\"/>\n"
"    </method>\n"
"    <method name=\"sendMessage\">\n"
"      <arg direction=\"in\" type=\"s\" name=\"to\"/>\n"
"      <arg direction=\"in\" type=\"s\" name=\"subject\"/>\n"
"      <arg direction=\"in\" type=\"s\" name=\"body\"/>\n"
"    </method>\n"
"    <method name=\"groupChatInvite\">\n"
"      <arg direction=\"in\" type=\"s\" name=\"room\"/>\n"
"      <arg direction=\"in\" type=\"s\" name=\"jid\"/>\n"
"      <arg direction=\"in\" type=\"s\" name=\"msg\"/>\n"
"    </method>\n"
"    <method name=\"subscribe\">\n"
"      <arg direction=\"in\" type=\"s\" name=\"jid\"/>\n"
"      <arg direction=\"in\" type=\"s\" name=\"nick\"/>\n"
"    </method>\n"
"    <method name=\"subscribe\">\n"
"      <arg direction=\"in\" type=\"s\" name=\"jid\"/>\n"
"    </method>\n"
"    <method name=\"unsubscribe\">\n"
"      <arg direction=\"in\" type=\"s\" name=\"jid\"/>\n"
"    </method>\n"
"    <method name=\"acceptSubscription\">\n"
"      <arg direction=\"in\" type=\"s\" name=\"jid\"/>\n"
"    </method>\n"
"  </interface>\n"
        "")
public:
    CvMsgAccountAdaptor(QObject *parent);
    virtual ~CvMsgAccountAdaptor();

public: // PROPERTIES
public Q_SLOTS: // METHODS
    void acceptSubscription(const QString &jid);
    void groupChatChangeNick(const QString &host, const QString &room, const QString &nick, int status);
    void groupChatInvite(const QString &room, const QString &jid, const QString &msg);
    bool groupChatJoin(const QString &host, const QString &room, const QString &nick);
    bool groupChatJoin(const QString &host, const QString &room, const QString &nick, const QString &password);
    bool groupChatJoin(const QString &host, const QString &room, const QString &nick, const QString &password, int maxchars);
    bool groupChatJoin(const QString &host, const QString &room, const QString &nick, const QString &password, int maxchars, int maxstanzas);
    bool groupChatJoin(const QString &host, const QString &room, const QString &nick, const QString &password, int maxchars, int maxstanzas, int seconds);
    bool groupChatJoin(const QString &host, const QString &room, const QString &nick, const QString &password, int maxchars, int maxstanzas, int seconds, int Status);
    void groupChatLeave(const QString &host, const QString &room);
    void groupChatSetStatus(const QString &host, const QString &room, int status);
    int initAccount(const QString &j, const QString &p);
    int initAccount(const QString &j, const QString &p, bool overwrite);
    int login(int status);
    void logout();
    void sendMessage(const QString &to, const QString &subject, const QString &body);
    int setPresence(int status);
    void subscribe(const QString &jid);
    void subscribe(const QString &jid, const QString &nick);
    void unsubscribe(const QString &jid);
Q_SIGNALS: // SIGNALS
    void accountError(int errCode, const QString &details);
    void accountPresenceChanged(const QString &jid, int presence);
    void accountStateChanged(const QString &jid, int state);
    void connectionClose();
    void groupChatError(const QString &j, int code, const QString &detail);
    void groupChatInvited(const QString &gc, const QString &from, const QString &reason);
    void groupChatJoined(const QString &j);
    void groupChatLeft(const QString &j);
    void groupChatPresence(const QString &j, int status);
    void loginSuccess(const QString &jid);
    void messageReceived(const QString &from, const QString &to, const QString &subject, const QString &body, const QString &time);
    void presenceChanged(int status);
    void subscriptionAccepted(const QString &j);
    void subscriptionDenied(const QString &j);
    void subscriptionReceived(const QString &j, const QString &nick);
};

#endif
