/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -c BfcpServerAdaptor -a BfcpServerAdaptor.h:BfcpServerAdaptor.cpp .\com.dcampus.coolview.BfcpServer.xml
 *
 * qdbusxml2cpp is Copyright (C) 2013 Digia Plc and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include "BfcpServerAdaptor.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Implementation of adaptor class BfcpServerAdaptor
 */

BfcpServerAdaptor::BfcpServerAdaptor(QObject *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

BfcpServerAdaptor::~BfcpServerAdaptor()
{
    // destructor
}

void BfcpServerAdaptor::AddConference(uint conference_id, const QByteArray &conference_arg)
{
    // handle method call com.dcampus.coolview.BfcpServer.AddConference
    QMetaObject::invokeMethod(parent(), "AddConference", Q_ARG(uint, conference_id), Q_ARG(QByteArray, conference_arg));
}

void BfcpServerAdaptor::AddFloor(uint conference_id, ushort floor_id, const QByteArray &floor_arg)
{
    // handle method call com.dcampus.coolview.BfcpServer.AddFloor
    QMetaObject::invokeMethod(parent(), "AddFloor", Q_ARG(uint, conference_id), Q_ARG(ushort, floor_id), Q_ARG(QByteArray, floor_arg));
}

void BfcpServerAdaptor::AddUser(uint conference_id, ushort user_id, const QByteArray &user_arg)
{
    // handle method call com.dcampus.coolview.BfcpServer.AddUser
    QMetaObject::invokeMethod(parent(), "AddUser", Q_ARG(uint, conference_id), Q_ARG(ushort, user_id), Q_ARG(QByteArray, user_arg));
}

void BfcpServerAdaptor::GetConferenceIDs()
{
    // handle method call com.dcampus.coolview.BfcpServer.GetConferenceIDs
    QMetaObject::invokeMethod(parent(), "GetConferenceIDs");
}

void BfcpServerAdaptor::GetConferenceInfo(uint conference_id)
{
    // handle method call com.dcampus.coolview.BfcpServer.GetConferenceInfo
    QMetaObject::invokeMethod(parent(), "GetConferenceInfo", Q_ARG(uint, conference_id));
}

void BfcpServerAdaptor::ModifyConference(uint conference_id, const QByteArray &conference_arg)
{
    // handle method call com.dcampus.coolview.BfcpServer.ModifyConference
    QMetaObject::invokeMethod(parent(), "ModifyConference", Q_ARG(uint, conference_id), Q_ARG(QByteArray, conference_arg));
}

void BfcpServerAdaptor::ModifyFloor(uint conference_id, ushort floor_id, const QByteArray &floor_arg)
{
    // handle method call com.dcampus.coolview.BfcpServer.ModifyFloor
    QMetaObject::invokeMethod(parent(), "ModifyFloor", Q_ARG(uint, conference_id), Q_ARG(ushort, floor_id), Q_ARG(QByteArray, floor_arg));
}

void BfcpServerAdaptor::Quit()
{
    // handle method call com.dcampus.coolview.BfcpServer.Quit
    QMetaObject::invokeMethod(parent(), "Quit");
}

void BfcpServerAdaptor::RemoveChair(uint conference_id, ushort floor_id)
{
    // handle method call com.dcampus.coolview.BfcpServer.RemoveChair
    QMetaObject::invokeMethod(parent(), "RemoveChair", Q_ARG(uint, conference_id), Q_ARG(ushort, floor_id));
}

void BfcpServerAdaptor::RemoveConference(uint conference_id)
{
    // handle method call com.dcampus.coolview.BfcpServer.RemoveConference
    QMetaObject::invokeMethod(parent(), "RemoveConference", Q_ARG(uint, conference_id));
}

void BfcpServerAdaptor::RemoveFloor(uint conference_id, ushort floor_id)
{
    // handle method call com.dcampus.coolview.BfcpServer.RemoveFloor
    QMetaObject::invokeMethod(parent(), "RemoveFloor", Q_ARG(uint, conference_id), Q_ARG(ushort, floor_id));
}

void BfcpServerAdaptor::RemoveUser(uint conference_id, ushort user_id)
{
    // handle method call com.dcampus.coolview.BfcpServer.RemoveUser
    QMetaObject::invokeMethod(parent(), "RemoveUser", Q_ARG(uint, conference_id), Q_ARG(ushort, user_id));
}

void BfcpServerAdaptor::SetChair(uint conference_id, ushort floor_id, ushort user_id)
{
    // handle method call com.dcampus.coolview.BfcpServer.SetChair
    QMetaObject::invokeMethod(parent(), "SetChair", Q_ARG(uint, conference_id), Q_ARG(ushort, floor_id), Q_ARG(ushort, user_id));
}

void BfcpServerAdaptor::Start(const QByteArray &server_arg)
{
    // handle method call com.dcampus.coolview.BfcpServer.Start
    QMetaObject::invokeMethod(parent(), "Start", Q_ARG(QByteArray, server_arg));
}

void BfcpServerAdaptor::Stop()
{
    // handle method call com.dcampus.coolview.BfcpServer.Stop
    QMetaObject::invokeMethod(parent(), "Stop");
}

