/*
 * This file was generated by qdbusxml2cpp version 0.7
 * Command line was: qdbusxml2cpp -v -c CvPerfMonitorIf -p CvPerfMonitorIf.h:CvPerfMonitorIf.cpp .\com.dcampus.coolview.performance.monitor.xml
 *
 * qdbusxml2cpp is Copyright (C) 2010 Nokia Corporation and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#include "CvPerfMonitorIf.h"

/*
 * Implementation of interface class CvPerfMonitorIf
 */

CvPerfMonitorIf::CvPerfMonitorIf(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent)
    : QDBusAbstractInterface(service, path, staticInterfaceName(), connection, parent)
{
}

CvPerfMonitorIf::~CvPerfMonitorIf()
{
}

