/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -c serviceTestAdaptor -a serviceTestAdaptor.h:serviceTestAdaptor.cpp .\com.dcampus.coolview.dbustest.xml
 *
 * qdbusxml2cpp is Copyright (C) 2015 Digia Plc and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include "serviceTestAdaptor.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Implementation of adaptor class serviceTestAdaptor
 */

serviceTestAdaptor::serviceTestAdaptor(QObject *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

serviceTestAdaptor::~serviceTestAdaptor()
{
    // destructor
}

int serviceTestAdaptor::DbusFunc()
{
    // handle method call com.dcampus.coolview.dbustest.DbusFunc
    int out0;
    QMetaObject::invokeMethod(parent(), "DbusFunc", Q_RETURN_ARG(int, out0));
    return out0;
}

