/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -c serviceTestAdaptor -a serviceTestAdaptor.h:serviceTestAdaptor.cpp .\com.dcampus.coolview.dbustest.xml
 *
 * qdbusxml2cpp is Copyright (C) 2015 Digia Plc and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef SERVICETESTADAPTOR_H_1462341918
#define SERVICETESTADAPTOR_H_1462341918

#include <QtCore/QObject>
#include <QtDBus/QtDBus>
QT_BEGIN_NAMESPACE
class QByteArray;
template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;
class QStringList;
class QVariant;
QT_END_NAMESPACE

/*
 * Adaptor class for interface com.dcampus.coolview.dbustest
 */
class serviceTestAdaptor: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "com.dcampus.coolview.dbustest")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"com.dcampus.coolview.dbustest\">\n"
"    <method name=\"DbusFunc\">\n"
"      <arg direction=\"out\" type=\"i\"/>\n"
"    </method>\n"
"  </interface>\n"
        "")
public:
    serviceTestAdaptor(QObject *parent);
    virtual ~serviceTestAdaptor();

public: // PROPERTIES
public Q_SLOTS: // METHODS
    int DbusFunc();
Q_SIGNALS: // SIGNALS
};

#endif
