/*
 * This file was generated by qdbusxml2cpp version 0.7
 * Command line was: qdbusxml2cpp -c CvMsdxClientServiceAdaptor -a CvMsdxClientServiceAdaptor.h:CvMsdxClientServiceAdaptor.cpp .\com.coolview.cvmsdxclient.xml
 *
 * qdbusxml2cpp is Copyright (C) 2010 Nokia Corporation and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef CVMSDXCLIENTSERVICEADAPTOR_H_1285570915
#define CVMSDXCLIENTSERVICEADAPTOR_H_1285570915

#include <QtCore/QObject>
#include <QtDBus/QtDBus>
class QByteArray;
template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;
class QStringList;
class QVariant;

/*
 * Adaptor class for interface com.coolview.cvmsdxclient
 */
class CvMsdxClientServiceAdaptor: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "com.coolview.cvmsdxclient")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"com.coolview.cvmsdxclient\">\n"
"    <method name=\"client_request\">\n"
"      <annotation value=\"__client_request_cb\" name=\"org.freedesktop.DBus.GLib.CSymbol\"/>\n"
"      <arg direction=\"in\" type=\"i\" name=\"action_id\"/>   //?????????????API??ID&#xd;\n"
"       <arg direction=\"in\" type=\"ay\" name=\"input_garray\"/>  //????Garray?????client????????????????????????server&#xd;\n"
"      <arg direction=\"out\" type=\"i\" name=\"result\"/>\n"
"    </method>\n"
"  </interface>\n"
        "")
public:
    CvMsdxClientServiceAdaptor(QObject *parent);
    virtual ~CvMsdxClientServiceAdaptor();

public: // PROPERTIES
public Q_SLOTS: // METHODS
    int client_request(int action_id, const QByteArray &input_garray);
Q_SIGNALS: // SIGNALS
};

#endif
