/*
 * This file was generated by qdbusxml2cpp version 0.7
 * Command line was: qdbusxml2cpp -c CvTestMediaAdaptor -a CvTestMediaAdaptor.h:CvTestMediaAdaptor.cpp .\com.dcampus.coolview.channel.type.testMedia.xml
 *
 * qdbusxml2cpp is Copyright (C) 2010 Nokia Corporation and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include "CvTestMediaAdaptor.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Implementation of adaptor class CvTestMediaAdaptor
 */

CvTestMediaAdaptor::CvTestMediaAdaptor(QObject *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

CvTestMediaAdaptor::~CvTestMediaAdaptor()
{
    // destructor
}

void CvTestMediaAdaptor::Destroy()
{
    // handle method call com.dcampus.coolview.channel.type.testMedia.Destroy
    QMetaObject::invokeMethod(parent(), "Destroy");
}

QByteArray CvTestMediaAdaptor::GetMediaInfo(int info_type)
{
    // handle method call com.dcampus.coolview.channel.type.testMedia.GetMediaInfo
    QByteArray output_garray;
    QMetaObject::invokeMethod(parent(), "GetMediaInfo", Q_RETURN_ARG(QByteArray, output_garray), Q_ARG(int, info_type));
    return output_garray;
}

void CvTestMediaAdaptor::Pause()
{
    // handle method call com.dcampus.coolview.channel.type.testMedia.Pause
    QMetaObject::invokeMethod(parent(), "Pause");
}

void CvTestMediaAdaptor::Run()
{
    // handle method call com.dcampus.coolview.channel.type.testMedia.Run
    QMetaObject::invokeMethod(parent(), "Run");
}

void CvTestMediaAdaptor::SetMediaInfo(int action_id, const QByteArray &input_garray)
{
    // handle method call com.dcampus.coolview.channel.type.testMedia.SetMediaInfo
    QMetaObject::invokeMethod(parent(), "SetMediaInfo", Q_ARG(int, action_id), Q_ARG(QByteArray, input_garray));
}

void CvTestMediaAdaptor::Stop()
{
    // handle method call com.dcampus.coolview.channel.type.testMedia.Stop
    QMetaObject::invokeMethod(parent(), "Stop");
}

