/*
 * This file was generated by qdbusxml2cpp version 0.7
 * Command line was: qdbusxml2cpp -v -c ConferenceRoomIf -p ConferenceRoomIf.h:ConferenceRoomIf.cpp .\com.coolview.ui.conferenceroom.xml
 *
 * qdbusxml2cpp is Copyright (C) 2010 Nokia Corporation and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#include "ConferenceRoomIf.h"

/*
 * Implementation of interface class ConferenceRoomIf
 */

ConferenceRoomIf::ConferenceRoomIf(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent)
    : QDBusAbstractInterface(service, path, staticInterfaceName(), connection, parent)
{
}

ConferenceRoomIf::~ConferenceRoomIf()
{
}

