/*
 * This file was generated by qdbusxml2cpp version 0.7
 * Command line was: qdbusxml2cpp -v -c ConferenceRoomIf -p ConferenceRoomIf.h:ConferenceRoomIf.cpp .\com.coolview.ui.conferenceroom.xml
 *
 * qdbusxml2cpp is Copyright (C) 2010 Nokia Corporation and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#ifndef CONFERENCEROOMIF_H_1347013352
#define CONFERENCEROOMIF_H_1347013352

#include <QtCore/QObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>
#include <QtDBus/QtDBus>

/*
 * Proxy class for interface com.coolview.ui.conferenceroom
 */
class ConferenceRoomIf: public QDBusAbstractInterface
{
    Q_OBJECT
public:
    static inline const char *staticInterfaceName()
    { return "com.coolview.ui.conferenceroom"; }

public:
    ConferenceRoomIf(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent = 0);

    ~ConferenceRoomIf();

public Q_SLOTS: // METHODS
    inline QDBusPendingReply<> AddMediaWindow(bool send, const QByteArray &input_garray, int screenIndex, int seet)
    {
        QList<QVariant> argumentList;
        argumentList << qVariantFromValue(send) << qVariantFromValue(input_garray) << qVariantFromValue(screenIndex) << qVariantFromValue(seet);
        return asyncCallWithArgumentList(QLatin1String("AddMediaWindow"), argumentList);
    }

    inline QDBusPendingReply<> ChangeLayout(int screenIndex, int displayModel)
    {
        QList<QVariant> argumentList;
        argumentList << qVariantFromValue(screenIndex) << qVariantFromValue(displayModel);
        return asyncCallWithArgumentList(QLatin1String("ChangeLayout"), argumentList);
    }

    inline QDBusPendingReply<> CloseMediaWindow(const QString &user_id)
    {
        QList<QVariant> argumentList;
        argumentList << qVariantFromValue(user_id);
        return asyncCallWithArgumentList(QLatin1String("CloseMediaWindow"), argumentList);
    }

    inline QDBusPendingReply<> CloseWindow()
    {
        QList<QVariant> argumentList;
        return asyncCallWithArgumentList(QLatin1String("CloseWindow"), argumentList);
    }

    inline QDBusPendingReply<> ExitConference()
    {
        QList<QVariant> argumentList;
        return asyncCallWithArgumentList(QLatin1String("ExitConference"), argumentList);
    }

    inline QDBusPendingReply<> ModifyMediaWindow(const QString &user_id, int actionIdex, const QByteArray &arguments)
    {
        QList<QVariant> argumentList;
        argumentList << qVariantFromValue(user_id) << qVariantFromValue(actionIdex) << qVariantFromValue(arguments);
        return asyncCallWithArgumentList(QLatin1String("ModifyMediaWindow"), argumentList);
    }

    inline QDBusPendingReply<> OpenScreenShareFile(const QString &filePath, int screenIndex)
    {
        QList<QVariant> argumentList;
        argumentList << qVariantFromValue(filePath) << qVariantFromValue(screenIndex);
        return asyncCallWithArgumentList(QLatin1String("OpenScreenShareFile"), argumentList);
    }

    inline QDBusPendingReply<> RecoveryRecvMediaProcess(const QByteArray &input_garray, int screenIndex, int seet)
    {
        QList<QVariant> argumentList;
        argumentList << qVariantFromValue(input_garray) << qVariantFromValue(screenIndex) << qVariantFromValue(seet);
        return asyncCallWithArgumentList(QLatin1String("RecoveryRecvMediaProcess"), argumentList);
    }

    inline QDBusPendingReply<> ShowRtcpMsg(int screenIndex, bool show)
    {
        QList<QVariant> argumentList;
        argumentList << qVariantFromValue(screenIndex) << qVariantFromValue(show);
        return asyncCallWithArgumentList(QLatin1String("ShowRtcpMsg"), argumentList);
    }

    inline QDBusPendingReply<> UpdateRtcpMsg(const QByteArray &input_garray)
    {
        QList<QVariant> argumentList;
        argumentList << qVariantFromValue(input_garray);
        return asyncCallWithArgumentList(QLatin1String("UpdateRtcpMsg"), argumentList);
    }

Q_SIGNALS: // SIGNALS
};

namespace com {
  namespace coolview {
    namespace ui {
      typedef ::ConferenceRoomIf conferenceroom;
    }
  }
}
#endif
