/*
 * This file was generated by qdbusxml2cpp version 0.7
 * Command line was: qdbusxml2cpp -c ConferenceRoomAdaptor -a ConferenceRoomAdaptor.h:ConferenceRoomAdaptor.cpp .\com.coolview.ui.conferenceroom.xml
 *
 * qdbusxml2cpp is Copyright (C) 2010 Nokia Corporation and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef CONFERENCEROOMADAPTOR_H_1347013344
#define CONFERENCEROOMADAPTOR_H_1347013344

#include <QtCore/QObject>
#include <QtDBus/QtDBus>
class QByteArray;
template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;
class QStringList;
class QVariant;

/*
 * Adaptor class for interface com.coolview.ui.conferenceroom
 */
class ConferenceRoomAdaptor: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "com.coolview.ui.conferenceroom")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"com.coolview.ui.conferenceroom\">\n"
"    <method name=\"AddMediaWindow\">\n"
"      <annotation value=\"__client_request_cb\" name=\"org.freedesktop.DBus.GLib.CSymbol\"/>\n"
"      <arg direction=\"in\" type=\"b\" name=\"send\"/>  	     //send or receive&#xd;\n"
"       <arg direction=\"in\" type=\"ay\" name=\"input_garray\"/>  //MediaInfo&#xd;\n"
"	   <arg direction=\"in\" type=\"i\" name=\"screenIndex\"/>  //Screen Index&#xd;\n"
"       <arg direction=\"in\" type=\"i\" name=\"seet\"/> 	     //video frame position&#xd;\n"
"    </method>\n"
"    <method name=\"CloseMediaWindow\">\n"
"      <arg direction=\"in\" type=\"s\" name=\"user_id\"/>  //user id&#xd;\n"
"    </method>\n"
"    <method name=\"ChangeLayout\">\n"
"      <arg direction=\"in\" type=\"i\" name=\"screenIndex\"/>	//Screen Index&#xd;\n"
"       <arg direction=\"in\" type=\"i\" name=\"displayModel\"/>  //display model for video windows&#xd;\n"
"    </method>\n"
"    <method name=\"ShowRtcpMsg\">\n"
"      <arg direction=\"in\" type=\"i\" name=\"screenIndex\"/>\n"
"      <arg direction=\"in\" type=\"b\" name=\"show\"/>\n"
"    </method>\n"
"    <method name=\"UpdateRtcpMsg\">\n"
"      <annotation value=\"__client_request_cb\" name=\"org.freedesktop.DBus.GLib.CSymbol\"/>\n"
"      <arg direction=\"in\" type=\"ay\" name=\"input_garray\"/>  //RtcpInfo&#xd;\n"
"    </method>\n"
"    <method name=\"ModifyMediaWindow\">\n"
"      <arg direction=\"in\" type=\"s\" name=\"user_id\"/>\n"
"      <arg direction=\"in\" type=\"i\" name=\"actionIdex\"/>\n"
"      <arg direction=\"in\" type=\"ay\" name=\"arguments\"/>\n"
"    </method>\n"
"    <method name=\"OpenScreenShareFile\">\n"
"      <arg direction=\"in\" type=\"s\" name=\"filePath\"/>\n"
"      <arg direction=\"in\" type=\"i\" name=\"screenIndex\"/>\n"
"    </method>\n"
"    <method name=\"CloseWindow\"/>\n"
"    <method name=\"ExitConference\"/>\n"
"    <method name=\"RecoveryRecvMediaProcess\">\n"
"      <arg direction=\"in\" type=\"ay\" name=\"input_garray\"/>  //MediaInfo&#xd;\n"
"	   <arg direction=\"in\" type=\"i\" name=\"screenIndex\"/>  //Screen Index&#xd;\n"
"       <arg direction=\"in\" type=\"i\" name=\"seet\"/> 	     //video frame position&#xd;\n"
"    </method>\n"
"  </interface>\n"
        "")
public:
    ConferenceRoomAdaptor(QObject *parent);
    virtual ~ConferenceRoomAdaptor();

public: // PROPERTIES
public Q_SLOTS: // METHODS
    void AddMediaWindow(bool send, const QByteArray &input_garray, int screenIndex, int seet);
    void ChangeLayout(int screenIndex, int displayModel);
    void CloseMediaWindow(const QString &user_id);
    void CloseWindow();
    void ExitConference();
    void ModifyMediaWindow(const QString &user_id, int actionIdex, const QByteArray &arguments);
    void OpenScreenShareFile(const QString &filePath, int screenIndex);
    void RecoveryRecvMediaProcess(const QByteArray &input_garray, int screenIndex, int seet);
    void ShowRtcpMsg(int screenIndex, bool show);
    void UpdateRtcpMsg(const QByteArray &input_garray);
Q_SIGNALS: // SIGNALS
};

#endif
