/*
 * This file was generated by qdbusxml2cpp version 0.7
 * Command line was: qdbusxml2cpp -v -c TelecontrollerIf -p TelecontrollerIf.h:TelecontrollerIf.cpp .\com.dcampus.coolview.controller.telecontroller.xml
 *
 * qdbusxml2cpp is Copyright (C) 2010 Nokia Corporation and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#ifndef TELECONTROLLERIF_H_1288602986
#define TELECONTROLLERIF_H_1288602986

#include <QtCore/QObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>
#include <QtDBus/QtDBus>

/*
 * Proxy class for interface com.dcampus.coolview.controller.telecontroller
 */
class TelecontrollerIf: public QDBusAbstractInterface
{
    Q_OBJECT
public:
    static inline const char *staticInterfaceName()
    { return "com.dcampus.coolview.controller.telecontroller"; }

public:
    TelecontrollerIf(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent = 0);

    ~TelecontrollerIf();

public Q_SLOTS: // METHODS
    inline QDBusReply<void> TeleInfo(const QString &info)
    {
        QList<QVariant> argumentList;
        argumentList << qVariantFromValue(info);
		return callWithArgumentList(QDBus::NoBlock,QLatin1String("TeleInfo"), argumentList);
    }

Q_SIGNALS: // SIGNALS
};

namespace com {
  namespace dcampus {
    namespace coolview {
      namespace controller {
        typedef ::TelecontrollerIf telecontroller;
      }
    }
  }
}
#endif
