/*
 * This file was generated by qdbusxml2cpp version 0.7
 * Command line was: qdbusxml2cpp -c CvScreenMediaAdaptor -a CvScreenMediaAdaptor.h:CvScreenMediaAdaptor.cpp .\com.dcampus.coolview.channel.type.screenMedia.xml
 *
 * qdbusxml2cpp is Copyright (C) 2010 Nokia Corporation and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include "CvScreenMediaAdaptor.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Implementation of adaptor class CvScreenMediaAdaptor
 */

CvScreenMediaAdaptor::CvScreenMediaAdaptor(QObject *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

CvScreenMediaAdaptor::~CvScreenMediaAdaptor()
{
    // destructor
}

void CvScreenMediaAdaptor::Destroy()
{
    // handle method call com.dcampus.coolview.channel.type.screenMedia.Destroy
    QMetaObject::invokeMethod(parent(), "Destroy");
}

QByteArray CvScreenMediaAdaptor::GetMediaInfo(int info_type)
{
    // handle method call com.dcampus.coolview.channel.type.screenMedia.GetMediaInfo
    QByteArray output_garray;
    QMetaObject::invokeMethod(parent(), "GetMediaInfo", Q_RETURN_ARG(QByteArray, output_garray), Q_ARG(int, info_type));
    return output_garray;
}

void CvScreenMediaAdaptor::Pause()
{
    // handle method call com.dcampus.coolview.channel.type.screenMedia.Pause
    QMetaObject::invokeMethod(parent(), "Pause");
}

void CvScreenMediaAdaptor::Run()
{
    // handle method call com.dcampus.coolview.channel.type.screenMedia.Run
    QMetaObject::invokeMethod(parent(), "Run");
}

void CvScreenMediaAdaptor::SetMediaInfo(int action_id, const QByteArray &input_garray)
{
    // handle method call com.dcampus.coolview.channel.type.screenMedia.SetMediaInfo
    QMetaObject::invokeMethod(parent(), "SetMediaInfo", Q_ARG(int, action_id), Q_ARG(QByteArray, input_garray));
}

void CvScreenMediaAdaptor::Stop()
{
    // handle method call com.dcampus.coolview.channel.type.screenMedia.Stop
    QMetaObject::invokeMethod(parent(), "Stop");
}

