/*
 * This file was generated by qdbusxml2cpp version 0.7
 * Command line was: qdbusxml2cpp -c CvStreamedMediaAdaptor -a CvStreamedMediaAdaptor.h:CvStreamedMediaAdaptor.cpp .\com.dcampus.coolview.channel.type.streamedMedia.xml
 *
 * qdbusxml2cpp is Copyright (C) 2010 Nokia Corporation and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include "CvStreamedMediaAdaptor.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Implementation of adaptor class CvStreamedMediaAdaptor
 */

CvStreamedMediaAdaptor::CvStreamedMediaAdaptor(QObject *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

CvStreamedMediaAdaptor::~CvStreamedMediaAdaptor()
{
    // destructor
}

void CvStreamedMediaAdaptor::Destroy()
{
    // handle method call com.dcampus.coolview.channel.type.streamedMedia.Destroy
    QMetaObject::invokeMethod(parent(), "Destroy");
}

QByteArray CvStreamedMediaAdaptor::GetMediaInfo(int info_type)
{
    // handle method call com.dcampus.coolview.channel.type.streamedMedia.GetMediaInfo
    QByteArray output_garray;
    QMetaObject::invokeMethod(parent(), "GetMediaInfo", Q_RETURN_ARG(QByteArray, output_garray), Q_ARG(int, info_type));
    return output_garray;
}

void CvStreamedMediaAdaptor::Pause()
{
    // handle method call com.dcampus.coolview.channel.type.streamedMedia.Pause
    QMetaObject::invokeMethod(parent(), "Pause");
}

void CvStreamedMediaAdaptor::Run()
{
    // handle method call com.dcampus.coolview.channel.type.streamedMedia.Run
    QMetaObject::invokeMethod(parent(), "Run");
}

void CvStreamedMediaAdaptor::SetMediaInfo(int action_id, const QByteArray &input_garray)
{
    // handle method call com.dcampus.coolview.channel.type.streamedMedia.SetMediaInfo
    QMetaObject::invokeMethod(parent(), "SetMediaInfo", Q_ARG(int, action_id), Q_ARG(QByteArray, input_garray));
}

void CvStreamedMediaAdaptor::Stop()
{
    // handle method call com.dcampus.coolview.channel.type.streamedMedia.Stop
    QMetaObject::invokeMethod(parent(), "Stop");
}

