/*
 * This file was generated by qdbusxml2cpp version 0.7
 * Command line was: qdbusxml2cpp -v -c MobiControllerIf -p MobiControllerIf.h:MobiControllerIf.cpp com.dcampus.coolview.controller.mobicontroller.xml
 *
 * qdbusxml2cpp is Copyright (C) 2010 Nokia Corporation and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#include "MobiControllerIf.h"

/*
 * Implementation of interface class MobiControllerIf
 */

MobiControllerIf::MobiControllerIf(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent)
    : QDBusAbstractInterface(service, path, staticInterfaceName(), connection, parent)
{
}

MobiControllerIf::~MobiControllerIf()
{
}

