/*
 * This file was generated by qdbusxml2cpp version 0.7
 * Command line was: qdbusxml2cpp -v -c MobiControllerIf -p MobiControllerIf.h:MobiControllerIf.cpp com.dcampus.coolview.controller.mobicontroller.xml
 *
 * qdbusxml2cpp is Copyright (C) 2010 Nokia Corporation and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#ifndef MOBICONTROLLERIF_H_1290144515
#define MOBICONTROLLERIF_H_1290144515

#include <QtCore/QObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>
#include <QtDBus/QtDBus>

/*
 * Proxy class for interface com.dcampus.coolview.controller.mobilecontroller
 */
class MobiControllerIf: public QDBusAbstractInterface
{
    Q_OBJECT
public:
    static inline const char *staticInterfaceName()
    { return "com.dcampus.coolview.controller.mobilecontroller"; }

public:
    MobiControllerIf(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent = 0);

    ~MobiControllerIf();

public Q_SLOTS: // METHODS
    inline QDBusPendingReply<> RefreshDeviceList()
    {
        QList<QVariant> argumentList;
        return asyncCallWithArgumentList(QLatin1String("RefreshDeviceList"), argumentList);
    }

    inline QDBusPendingReply<> SetDevice(const QString &device_name)
    {
        QList<QVariant> argumentList;
        argumentList << qVariantFromValue(device_name);
        return asyncCallWithArgumentList(QLatin1String("SetDevice"), argumentList);
    }

    inline QDBusPendingReply<> TeleCommand(int action_id, const QByteArray &input_garray)
    {
        QList<QVariant> argumentList;
        argumentList << qVariantFromValue(action_id) << qVariantFromValue(input_garray);
        return asyncCallWithArgumentList(QLatin1String("TeleCommand"), argumentList);
    }

Q_SIGNALS: // SIGNALS
    void DeviceListReady(const QString &device_list);
    void Disconnected(const QString &device_name);
    void TeleNotify(const QString &notify);
};

namespace com {
  namespace dcampus {
    namespace coolview {
      namespace controller {
        typedef ::MobiControllerIf mobilecontroller;
      }
    }
  }
}
#endif
