/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -c TxControllerAdaptor -a TxControllerAdaptor.h:TxControllerAdaptor.cpp .\com.dcampus.coolview.txController.xml
 *
 * qdbusxml2cpp is Copyright (C) 2013 Digia Plc and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef TXCONTROLLERADAPTOR_H_1431311812
#define TXCONTROLLERADAPTOR_H_1431311812

#include <QtCore/QObject>
#include <QtDBus/QtDBus>
QT_BEGIN_NAMESPACE
class QByteArray;
template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;
class QStringList;
class QVariant;
QT_END_NAMESPACE

/*
 * Adaptor class for interface com.dcampus.coolview.txController
 */
class TxControllerAdaptor: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "com.dcampus.coolview.txController")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"com.dcampus.coolview.txController\">\n"
"    <method name=\"ControlRecord\">\n"
"      <arg direction=\"in\" type=\"i\" name=\"op\"/>\n"
"      <arg direction=\"in\" type=\"ay\" name=\"param\"/>\n"
"      <arg direction=\"out\" type=\"i\" name=\"result\"/>\n"
"    </method>\n"
"    <method name=\"GetRecordStatus\">\n"
"      <arg direction=\"in\" type=\"s\" name=\"focus\"/>\n"
"      <arg direction=\"in\" type=\"s\" name=\"uri\"/>\n"
"      <arg direction=\"out\" type=\"ay\" name=\"status\"/>\n"
"    </method>\n"
"  </interface>\n"
        "")
public:
    TxControllerAdaptor(QObject *parent);
    virtual ~TxControllerAdaptor();

public: // PROPERTIES
public Q_SLOTS: // METHODS
    int ControlRecord(int op, const QByteArray &param);
    QByteArray GetRecordStatus(const QString &focus, const QString &uri);
Q_SIGNALS: // SIGNALS
};

#endif
