/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -c TxControllerAdaptor -a TxControllerAdaptor.h:TxControllerAdaptor.cpp .\com.dcampus.coolview.txController.xml
 *
 * qdbusxml2cpp is Copyright (C) 2013 Digia Plc and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include "TxControllerAdaptor.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Implementation of adaptor class TxControllerAdaptor
 */

TxControllerAdaptor::TxControllerAdaptor(QObject *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

TxControllerAdaptor::~TxControllerAdaptor()
{
    // destructor
}

int TxControllerAdaptor::ControlRecord(int op, const QByteArray &param)
{
    // handle method call com.dcampus.coolview.txController.ControlRecord
    int result;
    QMetaObject::invokeMethod(parent(), "ControlRecord", Q_RETURN_ARG(int, result), Q_ARG(int, op), Q_ARG(QByteArray, param));
    return result;
}

QByteArray TxControllerAdaptor::GetRecordStatus(const QString &focus, const QString &uri)
{
    // handle method call com.dcampus.coolview.txController.GetRecordStatus
    QByteArray status;
    QMetaObject::invokeMethod(parent(), "GetRecordStatus", Q_RETURN_ARG(QByteArray, status), Q_ARG(QString, focus), Q_ARG(QString, uri));
    return status;
}

