/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -c TxMonitorAdaptor -a TxMonitorAdaptor.h:TxMonitorAdaptor.cpp .\com.dcampus.coolview.txMonitor.xml
 *
 * qdbusxml2cpp is Copyright (C) 2013 Digia Plc and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef TXMONITORADAPTOR_H_1426323405
#define TXMONITORADAPTOR_H_1426323405

#include <QtCore/QObject>
#include <QtDBus/QtDBus>
QT_BEGIN_NAMESPACE
class QByteArray;
template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;
class QStringList;
class QVariant;
QT_END_NAMESPACE

/*
 * Adaptor class for interface com.dcampus.coolview.txMonitor
 */
class TxMonitorAdaptor: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "com.dcampus.coolview.txMonitor")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"com.dcampus.coolview.txMonitor\">\n"
"    <method name=\"ReportRecStat\">\n"
"      <arg direction=\"in\" type=\"i\" name=\"stat_type\"/>\n"
"      <arg direction=\"in\" type=\"ay\" name=\"data_garray\"/>\n"
"    </method>\n"
"  </interface>\n"
        "")
public:
    TxMonitorAdaptor(QObject *parent);
    virtual ~TxMonitorAdaptor();

public: // PROPERTIES
public Q_SLOTS: // METHODS
    void ReportRecStat(int stat_type, const QByteArray &data_garray);
Q_SIGNALS: // SIGNALS
};

#endif
