/*
 * This file was generated by qdbusxml2cpp version 0.7
 * Command line was: qdbusxml2cpp com.dcampus.coolview.im.jabber.xml -c CvMsgAccountProxy -p accountproxy.h:accountproxy.cpp
 *
 * qdbusxml2cpp is Copyright (C) 2010 Nokia Corporation and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#include "accountproxy.h"

/*
 * Implementation of interface class CvMsgAccountProxy
 */

CvMsgAccountProxy::CvMsgAccountProxy(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent)
    : QDBusAbstractInterface(service, path, staticInterfaceName(), connection, parent)
{
}

CvMsgAccountProxy::~CvMsgAccountProxy()
{
}

