/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -c CvCoreAdaptor -a CvCoreAdaptor.h:CvCoreAdaptor.cpp .\com.dcampus.coolview.core.xml
 *
 * qdbusxml2cpp is Copyright (C) 2015 Digia Plc and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef CVCOREADAPTOR_H_1462276093
#define CVCOREADAPTOR_H_1462276093

#include <QtCore/QObject>
#include <QtDBus/QtDBus>
QT_BEGIN_NAMESPACE
class QByteArray;
template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;
class QStringList;
class QVariant;
QT_END_NAMESPACE

/*
 * Adaptor class for interface com.dcampus.coolview.core
 */
class CvCoreAdaptor: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "com.dcampus.coolview.core")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"com.dcampus.coolview.core\">\n"
"    <method name=\"TeleCommand\">\n"
"      <arg direction=\"in\" type=\"i\" name=\"command_index\"/>\n"
"      <arg direction=\"in\" type=\"ay\" name=\"intput_array\"/>\n"
"    </method>\n"
"    <method name=\"MoveToMainThreadSlot\"/>\n"
"    <method name=\"CloseCoolViewSlotDbus\"/>\n"
"  </interface>\n"
        "")
public:
    CvCoreAdaptor(QObject *parent);
    virtual ~CvCoreAdaptor();

public: // PROPERTIES
public Q_SLOTS: // METHODS
    void CloseCoolViewSlotDbus();
    void MoveToMainThreadSlot();
    void TeleCommand(int command_index, const QByteArray &intput_array);
Q_SIGNALS: // SIGNALS
};

#endif
