/*
 * This file was generated by qdbusxml2cpp version 0.7
 * Command line was: qdbusxml2cpp -c TelecontrollerAdaptor -a TelecontrollerAdaptor.h:TelecontrollerAdaptor.cpp .\com.dcampus.coolview.controller.telecontroller.xml
 *
 * qdbusxml2cpp is Copyright (C) 2010 Nokia Corporation and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include "TelecontrollerAdaptor.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Implementation of adaptor class TelecontrollerAdaptor
 */

TelecontrollerAdaptor::TelecontrollerAdaptor(QObject *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

TelecontrollerAdaptor::~TelecontrollerAdaptor()
{
    // destructor
}

void TelecontrollerAdaptor::TeleInfo(int info_index, int subscribe_id, const QByteArray &input_array)
{
    // handle method call com.dcampus.coolview.controller.telecontroller.TeleInfo
    QMetaObject::invokeMethod(parent(), "TeleInfo", Q_ARG(int, info_index), Q_ARG(int, subscribe_id), Q_ARG(QByteArray, input_array));
}

