/*
 * This file was generated by qdbusxml2cpp version 0.7
 * Command line was: qdbusxml2cpp -c TelecontrollerAdaptor -a TelecontrollerAdaptor.h:TelecontrollerAdaptor.cpp .\com.dcampus.coolview.controller.telecontroller.xml
 *
 * qdbusxml2cpp is Copyright (C) 2010 Nokia Corporation and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef TELECONTROLLERADAPTOR_H_1300348561
#define TELECONTROLLERADAPTOR_H_1300348561

#include <QtCore/QObject>
#include <QtDBus/QtDBus>
class QByteArray;
template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;
class QStringList;
class QVariant;

/*
 * Adaptor class for interface com.dcampus.coolview.controller.telecontroller
 */
class TelecontrollerAdaptor: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "com.dcampus.coolview.controller.telecontroller")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"com.dcampus.coolview.controller.telecontroller\">\n"
"    <method name=\"TeleInfo\">\n"
"      <arg direction=\"in\" type=\"i\" name=\"info_index\"/>  //tele info index&#xd;\n"
"	   <arg direction=\"in\" type=\"i\" name=\"subscribe_id\"/>		//Tele info to specific controller&#xd;\n"
"	   <arg direction=\"in\" type=\"ay\" name=\"input_array\"/>\n"
"    </method>\n"
"  </interface>\n"
        "")
public:
    TelecontrollerAdaptor(QObject *parent);
    virtual ~TelecontrollerAdaptor();

public: // PROPERTIES
public Q_SLOTS: // METHODS
    void TeleInfo(int info_index, int subscribe_id, const QByteArray &input_array);
Q_SIGNALS: // SIGNALS
};

#endif
