HEADERS += \
           "D:/qutecom-2.2/wengophone/src/presentation/PChatHandler.h" \
           "D:/qutecom-2.2/wengophone/src/presentation/PConferenceCall.h" \
           "D:/qutecom-2.2/wengophone/src/presentation/PContactList.h" \
           "D:/qutecom-2.2/wengophone/src/presentation/PFactory.h" \
           "D:/qutecom-2.2/wengophone/src/presentation/PHistory.h" \
           "D:/qutecom-2.2/wengophone/src/presentation/PPhoneCall.h" \
           "D:/qutecom-2.2/wengophone/src/presentation/PPhoneLine.h" \
           "D:/qutecom-2.2/wengophone/src/presentation/PSms.h" \
           "D:/qutecom-2.2/wengophone/src/presentation/PSoftUpdate.h" \
           "D:/qutecom-2.2/wengophone/src/presentation/PSubscribe.h" \
           "D:/qutecom-2.2/wengophone/src/presentation/PUserProfile.h" \
           "D:/qutecom-2.2/wengophone/src/presentation/PUserProfileHandler.h" \
           "D:/qutecom-2.2/wengophone/src/presentation/PWenboxPlugin.h" \
           "D:/qutecom-2.2/wengophone/src/presentation/PWengoPhone.h" \
           "D:/qutecom-2.2/wengophone/src/presentation/PWsDirectory.h" \
           "D:/qutecom-2.2/wengophone/src/presentation/Presentation.h" \
           "D:/qutecom-2.2/wengophone/src/presentation/gtk/GtkFactory.h" \
           "D:/qutecom-2.2/wengophone/src/presentation/gtk/GtkWengoPhone.h" \
           "D:/qutecom-2.2/wengophone/src/presentation/gtk/GtkWengoPhoneLogger.h" \
           "D:/qutecom-2.2/wengophone/src/presentation/gtk/WidgetFactory.h" \
           "D:/qutecom-2.2/wengophone/src/presentation/gtk/phoneline/GtkPhoneLine.h" \
           "D:/qutecom-2.2/wengophone/src/presentation/qt/QtAbout.h" \
           "D:/qutecom-2.2/wengophone/src/presentation/qt/QtBrowserWidget.h" \
           "D:/qutecom-2.2/wengophone/src/presentation/qt/QtDialpad.h" \
           "D:/qutecom-2.2/wengophone/src/presentation/qt/QtEnumIMProtocol.h" \
           "D:/qutecom-2.2/wengophone/src/presentation/qt/QtFactory.h" \
           "D:/qutecom-2.2/wengophone/src/presentation/qt/QtHttpProxyLogin.h" \
           "D:/qutecom-2.2/wengophone/src/presentation/qt/QtIMAccountHelper.h" \
           "D:/qutecom-2.2/wengophone/src/presentation/qt/QtIMAccountMonitor.h" \
           "D:/qutecom-2.2/wengophone/src/presentation/qt/QtIdle.h" \
           "D:/qutecom-2.2/wengophone/src/presentation/qt/QtLanguage.h" \
           "D:/qutecom-2.2/wengophone/src/presentation/qt/QtNoWengoAlert.h" \
           "D:/qutecom-2.2/wengophone/src/presentation/qt/QtPresenceMenuManager.h" \
           "D:/qutecom-2.2/wengophone/src/presentation/qt/QtPresencePixmapHelper.h" \
           "D:/qutecom-2.2/wengophone/src/presentation/qt/QtSVGDialpad.h" \
           "D:/qutecom-2.2/wengophone/src/presentation/qt/QtSystray.h" \
           "D:/qutecom-2.2/wengophone/src/presentation/qt/QtToolBar.h" \
           "D:/qutecom-2.2/wengophone/src/presentation/qt/QtWengoPhone.h" \
           "D:/qutecom-2.2/wengophone/src/presentation/qt/QtWengoStyle.h" \
           "D:/qutecom-2.2/wengophone/src/presentation/qt/ToolTipLineEditProxy.h" \
           "D:/qutecom-2.2/wengophone/src/presentation/qt/WengoStyleLabelProxy.h" \
           "D:/qutecom-2.2/wengophone/src/presentation/qt/WinApp.h" \
           "D:/qutecom-2.2/wengophone/src/presentation/qt/callbar/QtCallBar.h" \
           "D:/qutecom-2.2/wengophone/src/presentation/qt/callbar/QtPhoneComboBox.h" \
           "D:/qutecom-2.2/wengophone/src/presentation/qt/chat/QtChatAvatarFrame.h" \
           "D:/qutecom-2.2/wengophone/src/presentation/qt/chat/QtChatAvatarWidget.h" \
           "D:/qutecom-2.2/wengophone/src/presentation/qt/chat/QtChatEditWidget.h" \
           "D:/qutecom-2.2/wengophone/src/presentation/qt/chat/QtChatHandler.h" \
           "D:/qutecom-2.2/wengophone/src/presentation/qt/chat/QtChatHistoryWidget.h" \
           "D:/qutecom-2.2/wengophone/src/presentation/qt/chat/QtChatLogViewer.h" \
           "D:/qutecom-2.2/wengophone/src/presentation/qt/chat/QtChatTabWidget.h" \
           "D:/qutecom-2.2/wengophone/src/presentation/qt/chat/QtChatTheme.h" \
           "D:/qutecom-2.2/wengophone/src/presentation/qt/chat/QtChatUtils.h" \
           "D:/qutecom-2.2/wengophone/src/presentation/qt/chat/QtChatWidget.h" \
           "D:/qutecom-2.2/wengophone/src/presentation/qt/chat/QtChatWindow.h" \
           "D:/qutecom-2.2/wengophone/src/presentation/qt/chat/QtWengoStyleBar.h" \
           "D:/qutecom-2.2/wengophone/src/presentation/qt/chat/chatroom/QtChatRoomInviteDlg.h" \
           "D:/qutecom-2.2/wengophone/src/presentation/qt/chat/chatroom/QtChatRoomListWidgetItem.h" \
           "D:/qutecom-2.2/wengophone/src/presentation/qt/chat/chatroom/QtChatRoomTreeWidgetItem.h" \
           "D:/qutecom-2.2/wengophone/src/presentation/qt/chat/emoticons/QtEmoticon.h" \
           "D:/qutecom-2.2/wengophone/src/presentation/qt/chat/emoticons/QtEmoticonButton.h" \
           "D:/qutecom-2.2/wengophone/src/presentation/qt/chat/emoticons/QtEmoticonsManager.h" \
           "D:/qutecom-2.2/wengophone/src/presentation/qt/chat/emoticons/QtEmoticonsWidget.h" \
           "D:/qutecom-2.2/wengophone/src/presentation/qt/conference/QtConferenceCallWidget.h" \
           "D:/qutecom-2.2/wengophone/src/presentation/qt/config/QtAccountSettings.h" \
           "D:/qutecom-2.2/wengophone/src/presentation/qt/config/QtAdvancedConfig.h" \
           "D:/qutecom-2.2/wengophone/src/presentation/qt/config/QtAdvancedSettings.h" \
           "D:/qutecom-2.2/wengophone/src/presentation/qt/config/QtAppearanceSettings.h" \
           "D:/qutecom-2.2/wengophone/src/presentation/qt/config/QtAudioSettings.h" \
           "D:/qutecom-2.2/wengophone/src/presentation/qt/config/QtCallForwardSettings.h" \
           "D:/qutecom-2.2/wengophone/src/presentation/qt/config/QtGeneralSettings.h" \
           "D:/qutecom-2.2/wengophone/src/presentation/qt/config/QtISettings.h" \
           "D:/qutecom-2.2/wengophone/src/presentation/qt/config/QtLanguagesSettings.h" \
           "D:/qutecom-2.2/wengophone/src/presentation/qt/config/QtNotificationSettings.h" \
           "D:/qutecom-2.2/wengophone/src/presentation/qt/config/QtPrivacySettings.h" \
           "D:/qutecom-2.2/wengophone/src/presentation/qt/config/QtSecuritySettings.h" \
           "D:/qutecom-2.2/wengophone/src/presentation/qt/config/QtVideoSettings.h" \
           "D:/qutecom-2.2/wengophone/src/presentation/qt/config/QtVoicemailSettings.h" \
           "D:/qutecom-2.2/wengophone/src/presentation/qt/config/QtWengoConfigDialog.h" \
           "D:/qutecom-2.2/wengophone/src/presentation/qt/contactlist/ContactGroupPopupMenu.h" \
           "D:/qutecom-2.2/wengophone/src/presentation/qt/contactlist/QtConferenceAction.h" \
           "D:/qutecom-2.2/wengophone/src/presentation/qt/contactlist/QtContact.h" \
           "D:/qutecom-2.2/wengophone/src/presentation/qt/contactlist/QtContactInfo.h" \
           "D:/qutecom-2.2/wengophone/src/presentation/qt/contactlist/QtContactList.h" \
           "D:/qutecom-2.2/wengophone/src/presentation/qt/contactlist/QtContactListManager.h" \
           "D:/qutecom-2.2/wengophone/src/presentation/qt/contactlist/QtContactManager.h" \
           "D:/qutecom-2.2/wengophone/src/presentation/qt/contactlist/QtContactMenu.h" \
           "D:/qutecom-2.2/wengophone/src/presentation/qt/contactlist/QtContactPixmap.h" \
           "D:/qutecom-2.2/wengophone/src/presentation/qt/contactlist/QtContactTreeKeyFilter.h" \
           "D:/qutecom-2.2/wengophone/src/presentation/qt/contactlist/QtContactTreeMouseFilter.h" \
           "D:/qutecom-2.2/wengophone/src/presentation/qt/contactlist/QtContactWidget.h" \
           "D:/qutecom-2.2/wengophone/src/presentation/qt/contactlist/QtRenameGroup.h" \
           "D:/qutecom-2.2/wengophone/src/presentation/qt/contactlist/QtTreeViewDelegate.h" \
           "D:/qutecom-2.2/wengophone/src/presentation/qt/filetransfer/QtFileTransfer.h" \
           "D:/qutecom-2.2/wengophone/src/presentation/qt/filetransfer/QtFileTransferAcceptDialog.h" \
           "D:/qutecom-2.2/wengophone/src/presentation/qt/filetransfer/QtFileTransferDownloadItem.h" \
           "D:/qutecom-2.2/wengophone/src/presentation/qt/filetransfer/QtFileTransferItem.h" \
           "D:/qutecom-2.2/wengophone/src/presentation/qt/filetransfer/QtFileTransferNotifyDialog.h" \
           "D:/qutecom-2.2/wengophone/src/presentation/qt/filetransfer/QtFileTransferUploadItem.h" \
           "D:/qutecom-2.2/wengophone/src/presentation/qt/filetransfer/QtFileTransferWidget.h" \
           "D:/qutecom-2.2/wengophone/src/presentation/qt/history/QtHistory.h" \
           "D:/qutecom-2.2/wengophone/src/presentation/qt/history/QtHistoryWidget.h" \
           "D:/qutecom-2.2/wengophone/src/presentation/qt/imaccount/QtAIMSettings.h" \
           "D:/qutecom-2.2/wengophone/src/presentation/qt/imaccount/QtGoogleTalkSettings.h" \
           "D:/qutecom-2.2/wengophone/src/presentation/qt/imaccount/QtICQSettings.h" \
           "D:/qutecom-2.2/wengophone/src/presentation/qt/imaccount/QtIMAccountManager.h" \
           "D:/qutecom-2.2/wengophone/src/presentation/qt/imaccount/QtIMAccountPlugin.h" \
           "D:/qutecom-2.2/wengophone/src/presentation/qt/imaccount/QtIMAccountSettings.h" \
           "D:/qutecom-2.2/wengophone/src/presentation/qt/imaccount/QtJabberSettings.h" \
           "D:/qutecom-2.2/wengophone/src/presentation/qt/imaccount/QtMSNSettings.h" \
           "D:/qutecom-2.2/wengophone/src/presentation/qt/imaccount/QtYahooSettings.h" \
           "D:/qutecom-2.2/wengophone/src/presentation/qt/imcontact/QtAddIMContact.h" \
           "D:/qutecom-2.2/wengophone/src/presentation/qt/imcontact/QtAdvancedIMContactManager.h" \
           "D:/qutecom-2.2/wengophone/src/presentation/qt/imcontact/QtIMContactItem.h" \
           "D:/qutecom-2.2/wengophone/src/presentation/qt/imcontact/QtIMContactManagerInterface.h" \
           "D:/qutecom-2.2/wengophone/src/presentation/qt/imcontact/QtSimpleIMContactManager.h" \
           "D:/qutecom-2.2/wengophone/src/presentation/qt/login/ILogin.h" \
           "D:/qutecom-2.2/wengophone/src/presentation/qt/login/QtAddAccount.h" \
           "D:/qutecom-2.2/wengophone/src/presentation/qt/login/QtAddAccountUtils.h" \
           "D:/qutecom-2.2/wengophone/src/presentation/qt/login/QtAddSIPAccount.h" \
           "D:/qutecom-2.2/wengophone/src/presentation/qt/login/QtAddWengoAccount.h" \
           "D:/qutecom-2.2/wengophone/src/presentation/qt/login/QtLogAccount.h" \
           "D:/qutecom-2.2/wengophone/src/presentation/qt/login/QtLoginDialog.h" \
           "D:/qutecom-2.2/wengophone/src/presentation/qt/macosx/QtMacApplication.h" \
           "D:/qutecom-2.2/wengophone/src/presentation/qt/phonecall/QtAudioSmileysWindow.h" \
           "D:/qutecom-2.2/wengophone/src/presentation/qt/phonecall/QtContactCallListWidget.h" \
           "D:/qutecom-2.2/wengophone/src/presentation/qt/phonecall/QtPhoneCall.h" \
           "D:/qutecom-2.2/wengophone/src/presentation/qt/phonecall/QtPhoneCallEventFilter.h" \
           "D:/qutecom-2.2/wengophone/src/presentation/qt/phonecall/QtVideo.h" \
           "D:/qutecom-2.2/wengophone/src/presentation/qt/phonecall/QtVideoQt.h" \
           "D:/qutecom-2.2/wengophone/src/presentation/qt/phonecall/QtVideoXV.h" \
           "D:/qutecom-2.2/wengophone/src/presentation/qt/phonecall/XVWindow.h" \
           "D:/qutecom-2.2/wengophone/src/presentation/qt/phoneline/QtPhoneLine.h" \
           "D:/qutecom-2.2/wengophone/src/presentation/qt/profile/QtProfileDetails.h" \
           "D:/qutecom-2.2/wengophone/src/presentation/qt/profile/QtUserProfile.h" \
           "D:/qutecom-2.2/wengophone/src/presentation/qt/profile/QtUserProfileHandler.h" \
           "D:/qutecom-2.2/wengophone/src/presentation/qt/profilebar/QtCreditWidget.h" \
           "D:/qutecom-2.2/wengophone/src/presentation/qt/profilebar/QtEventWidget.h" \
           "D:/qutecom-2.2/wengophone/src/presentation/qt/profilebar/QtIMAccountPresenceMenuManager.h" \
           "D:/qutecom-2.2/wengophone/src/presentation/qt/profilebar/QtIMProfileWidget.h" \
           "D:/qutecom-2.2/wengophone/src/presentation/qt/profilebar/QtProfileBar.h" \
           "D:/qutecom-2.2/wengophone/src/presentation/qt/statusbar/QtStatusBar.h" \
           "D:/qutecom-2.2/wengophone/src/presentation/qt/toaster/IQtToaster.h" \
           "D:/qutecom-2.2/wengophone/src/presentation/qt/toaster/QtCallToaster.h" \
           "D:/qutecom-2.2/wengophone/src/presentation/qt/toaster/QtChatToaster.h" \
           "D:/qutecom-2.2/wengophone/src/presentation/qt/toaster/QtToaster.h" \
           "D:/qutecom-2.2/wengophone/src/presentation/qt/webdirectory/QtWebDirectory.h" \
           "D:/qutecom-2.2/wengophone/src/presentation/qt/webservices/sms/QtSms.h" \
           "D:/qutecom-2.2/wengophone/src/presentation/qt/webservices/softupdate/QtBrowserSoftUpdate.h" \
           "D:/qutecom-2.2/wengophone/src/presentation/qt/webservices/softupdate/QtSoftUpdate.h" \
           "D:/qutecom-2.2/wengophone/src/presentation/qt/wenbox/QtWenboxPlugin.h" \
           "D:/qutecom-2.2/wengophone/src/presentation/xpcom/include/Command.h" \
           "D:/qutecom-2.2/wengophone/src/presentation/xpcom/include/Listener.h" \
           "D:/qutecom-2.2/wengophone/src/presentation/xpcom/src/ListenerList.h" \
           "D:/qutecom-2.2/wengophone/src/presentation/xpcom/src/XPCOMFactory.h" \
           "D:/qutecom-2.2/wengophone/src/presentation/xpcom/src/XPCOMIMHandler.h" \
           "D:/qutecom-2.2/wengophone/src/presentation/xpcom/src/XPCOMPhoneCall.h" \
           "D:/qutecom-2.2/wengophone/src/presentation/xpcom/src/XPCOMPhoneLine.h" \
           "D:/qutecom-2.2/wengophone/src/presentation/xpcom/src/XPCOMSms.h" \
           "D:/qutecom-2.2/wengophone/src/presentation/xpcom/src/XPCOMUserProfile.h" \
           "D:/qutecom-2.2/wengophone/src/presentation/xpcom/src/XPCOMWengoPhone.h" \
           "D:/qutecom-2.2/wengophone/src/presentation/xpcom/tests/MainWindow.h" \
           "D:/qutecom-2.2/crashreport/FtpUpload.h" \
           "D:/qutecom-2.2/crashreport/QtCrashReport.h" \
           "D:/qutecom-2.2/libs/qtutil/include/qtutil/AnimatedButton.h" \
           "D:/qutecom-2.2/libs/qtutil/include/qtutil/ClearLineEdit.h" \
           "D:/qutecom-2.2/libs/qtutil/include/qtutil/ClickableLabel.h" \
           "D:/qutecom-2.2/libs/qtutil/include/qtutil/CloseEventFilter.h" \
           "D:/qutecom-2.2/libs/qtutil/include/qtutil/DesktopService.h" \
           "D:/qutecom-2.2/libs/qtutil/include/qtutil/DropDownWindow.h" \
           "D:/qutecom-2.2/libs/qtutil/include/qtutil/EnabledChangeEventFilter.h" \
           "D:/qutecom-2.2/libs/qtutil/include/qtutil/EventFilter.h" \
           "D:/qutecom-2.2/libs/qtutil/include/qtutil/ExpandButton.h" \
           "D:/qutecom-2.2/libs/qtutil/include/qtutil/FSResourceFileEngineHandler.h" \
           "D:/qutecom-2.2/libs/qtutil/include/qtutil/IconLineEdit.h" \
           "D:/qutecom-2.2/libs/qtutil/include/qtutil/ImageSelector.h" \
           "D:/qutecom-2.2/libs/qtutil/include/qtutil/KeyEventFilter.h" \
           "D:/qutecom-2.2/libs/qtutil/include/qtutil/KeywordTranslator.h" \
           "D:/qutecom-2.2/libs/qtutil/include/qtutil/LanguageChangeEventFilter.h" \
           "D:/qutecom-2.2/libs/qtutil/include/qtutil/LinkLabel.h" \
           "D:/qutecom-2.2/libs/qtutil/include/qtutil/MacDesktopService.h" \
           "D:/qutecom-2.2/libs/qtutil/include/qtutil/MouseEventFilter.h" \
           "D:/qutecom-2.2/libs/qtutil/include/qtutil/NonResizeableWidget.h" \
           "D:/qutecom-2.2/libs/qtutil/include/qtutil/Object.h" \
           "D:/qutecom-2.2/libs/qtutil/include/qtutil/OsdButton.h" \
           "D:/qutecom-2.2/libs/qtutil/include/qtutil/PaintEventFilter.h" \
           "D:/qutecom-2.2/libs/qtutil/include/qtutil/PixmapMerging.h" \
           "D:/qutecom-2.2/libs/qtutil/include/qtutil/PostEvent.h" \
           "D:/qutecom-2.2/libs/qtutil/include/qtutil/QObjectThreadSafe.h" \
           "D:/qutecom-2.2/libs/qtutil/include/qtutil/QtThreadEvent.h" \
           "D:/qutecom-2.2/libs/qtutil/include/qtutil/ResizeEventFilter.h" \
           "D:/qutecom-2.2/libs/qtutil/include/qtutil/SafeConnect.h" \
           "D:/qutecom-2.2/libs/qtutil/include/qtutil/ScrollFrame.h" \
           "D:/qutecom-2.2/libs/qtutil/include/qtutil/StringListConvert.h" \
           "D:/qutecom-2.2/libs/qtutil/include/qtutil/ThreadEventFilter.h" \
           "D:/qutecom-2.2/libs/qtutil/include/qtutil/ThumbnailView.h" \
           "D:/qutecom-2.2/libs/qtutil/include/qtutil/ToolTipLineEdit.h" \
           "D:/qutecom-2.2/libs/qtutil/include/qtutil/UpQComboBox.h" \
           "D:/qutecom-2.2/libs/qtutil/include/qtutil/WengoStyleLabel.h" \
           "D:/qutecom-2.2/libs/qtutil/include/qtutil/Widget.h" \
           "D:/qutecom-2.2/libs/qtutil/include/qtutil/WidgetBackgroundImage.h" \
           "D:/qutecom-2.2/libs/qtutil/include/qtutil/WidgetFactory.h" \
           "D:/qutecom-2.2/libs/qtutil/include/qtutil/WidgetRatioEnforcer.h" \
           "D:/qutecom-2.2/libs/qtutil/include/qtutil/WidgetUtils.h" \
           "D:/qutecom-2.2/libs/qtutil/include/qtutil/WindowsDesktopService.h" \
           "D:/qutecom-2.2/libs/qtutil/include/qtutil/Wizard.h" \
           "D:/qutecom-2.2/libs/qtutil/include/qtutil/owqtutildll.h" \
           "D:/qutecom-2.2/libs/qtutil/src/QtThumbnailDirModel.h" \
           "D:/qutecom-2.2/libs/qtutil/src/QtThumbnailManager.h" \
           "D:/qutecom-2.2/libs/qtutil/tests/testdropdownwindow.h" \
           "D:/qutecom-2.2/libs/qtutil/tests/testexpandbutton.h" \
           "D:/qutecom-2.2/libs/qtutil/tests/testflashwindow.h" \
           "D:/qutecom-2.2/libs/qtutil/tests/testfsresourcefileenginehandler.h" \
           "D:/qutecom-2.2/libs/qtutil/tests/testkeywordtranslator.h" \
           "D:/qutecom-2.2/libs/qtutil/tests/testlineedit.h" \
           "D:/qutecom-2.2/libs/qtutil/tests/testlinklabel.h" \
           "D:/qutecom-2.2/libs/qtutil/tests/testscrollframe.h" \
           "D:/qutecom-2.2/libs/owbrowser/include/owbrowser/OWBrowser.h" \
           "D:/qutecom-2.2/libs/owbrowser/include/owbrowser/QtBrowser.h" \
           "D:/qutecom-2.2/libs/owbrowser/include/owbrowser/owbrowserdll.h" \


SOURCES += \
           "D:/qutecom-2.2/wengophone/src/presentation/PFactory.cpp" \
           "D:/qutecom-2.2/wengophone/src/presentation/gtk/GtkWengoPhone.cpp" \
           "D:/qutecom-2.2/wengophone/src/presentation/gtk/GtkWengoPhoneLogger.cpp" \
           "D:/qutecom-2.2/wengophone/src/presentation/gtk/WidgetFactory.cpp" \
           "D:/qutecom-2.2/wengophone/src/presentation/gtk/phoneline/GtkPhoneLine.cpp" \
           "D:/qutecom-2.2/wengophone/src/presentation/main.cpp" \
           "D:/qutecom-2.2/wengophone/src/presentation/qt/QtAbout.cpp" \
           "D:/qutecom-2.2/wengophone/src/presentation/qt/QtBrowserWidget.cpp" \
           "D:/qutecom-2.2/wengophone/src/presentation/qt/QtDialpad.cpp" \
           "D:/qutecom-2.2/wengophone/src/presentation/qt/QtEnumIMProtocol.cpp" \
           "D:/qutecom-2.2/wengophone/src/presentation/qt/QtFactory.cpp" \
           "D:/qutecom-2.2/wengophone/src/presentation/qt/QtHttpProxyLogin.cpp" \
           "D:/qutecom-2.2/wengophone/src/presentation/qt/QtIMAccountHelper.cpp" \
           "D:/qutecom-2.2/wengophone/src/presentation/qt/QtIMAccountMonitor.cpp" \
           "D:/qutecom-2.2/wengophone/src/presentation/qt/QtIdle.cpp" \
           "D:/qutecom-2.2/wengophone/src/presentation/qt/QtLanguage.cpp" \
           "D:/qutecom-2.2/wengophone/src/presentation/qt/QtNoWengoAlert.cpp" \
           "D:/qutecom-2.2/wengophone/src/presentation/qt/QtPresenceMenuManager.cpp" \
           "D:/qutecom-2.2/wengophone/src/presentation/qt/QtPresencePixmapHelper.cpp" \
           "D:/qutecom-2.2/wengophone/src/presentation/qt/QtSVGDialpad.cpp" \
           "D:/qutecom-2.2/wengophone/src/presentation/qt/QtSystray.cpp" \
           "D:/qutecom-2.2/wengophone/src/presentation/qt/QtToolBar.cpp" \
           "D:/qutecom-2.2/wengophone/src/presentation/qt/QtWengoPhone.cpp" \
           "D:/qutecom-2.2/wengophone/src/presentation/qt/QtWengoStyle.cpp" \
           "D:/qutecom-2.2/wengophone/src/presentation/qt/WinApp.cpp" \
           "D:/qutecom-2.2/wengophone/src/presentation/qt/callbar/QtCallBar.cpp" \
           "D:/qutecom-2.2/wengophone/src/presentation/qt/callbar/QtPhoneComboBox.cpp" \
           "D:/qutecom-2.2/wengophone/src/presentation/qt/chat/QtChatAvatarFrame.cpp" \
           "D:/qutecom-2.2/wengophone/src/presentation/qt/chat/QtChatAvatarWidget.cpp" \
           "D:/qutecom-2.2/wengophone/src/presentation/qt/chat/QtChatEditWidget.cpp" \
           "D:/qutecom-2.2/wengophone/src/presentation/qt/chat/QtChatHandler.cpp" \
           "D:/qutecom-2.2/wengophone/src/presentation/qt/chat/QtChatHistoryWidget.cpp" \
           "D:/qutecom-2.2/wengophone/src/presentation/qt/chat/QtChatLogViewer.cpp" \
           "D:/qutecom-2.2/wengophone/src/presentation/qt/chat/QtChatTabWidget.cpp" \
           "D:/qutecom-2.2/wengophone/src/presentation/qt/chat/QtChatTheme.cpp" \
           "D:/qutecom-2.2/wengophone/src/presentation/qt/chat/QtChatUtils.cpp" \
           "D:/qutecom-2.2/wengophone/src/presentation/qt/chat/QtChatWidget.cpp" \
           "D:/qutecom-2.2/wengophone/src/presentation/qt/chat/QtChatWindow.cpp" \
           "D:/qutecom-2.2/wengophone/src/presentation/qt/chat/QtWengoStyleBar.cpp" \
           "D:/qutecom-2.2/wengophone/src/presentation/qt/chat/chatroom/QtChatRoomInviteDlg.cpp" \
           "D:/qutecom-2.2/wengophone/src/presentation/qt/chat/chatroom/QtChatRoomListWidgetItem.cpp" \
           "D:/qutecom-2.2/wengophone/src/presentation/qt/chat/chatroom/QtChatRoomTreeWidgetItem.cpp" \
           "D:/qutecom-2.2/wengophone/src/presentation/qt/chat/emoticons/QtEmoticon.cpp" \
           "D:/qutecom-2.2/wengophone/src/presentation/qt/chat/emoticons/QtEmoticonButton.cpp" \
           "D:/qutecom-2.2/wengophone/src/presentation/qt/chat/emoticons/QtEmoticonsManager.cpp" \
           "D:/qutecom-2.2/wengophone/src/presentation/qt/chat/emoticons/QtEmoticonsWidget.cpp" \
           "D:/qutecom-2.2/wengophone/src/presentation/qt/conference/QtConferenceCallWidget.cpp" \
           "D:/qutecom-2.2/wengophone/src/presentation/qt/config/QtAccountSettings.cpp" \
           "D:/qutecom-2.2/wengophone/src/presentation/qt/config/QtAdvancedConfig.cpp" \
           "D:/qutecom-2.2/wengophone/src/presentation/qt/config/QtAdvancedSettings.cpp" \
           "D:/qutecom-2.2/wengophone/src/presentation/qt/config/QtAppearanceSettings.cpp" \
           "D:/qutecom-2.2/wengophone/src/presentation/qt/config/QtAudioSettings.cpp" \
           "D:/qutecom-2.2/wengophone/src/presentation/qt/config/QtCallForwardSettings.cpp" \
           "D:/qutecom-2.2/wengophone/src/presentation/qt/config/QtGeneralSettings.cpp" \
           "D:/qutecom-2.2/wengophone/src/presentation/qt/config/QtLanguagesSettings.cpp" \
           "D:/qutecom-2.2/wengophone/src/presentation/qt/config/QtNotificationSettings.cpp" \
           "D:/qutecom-2.2/wengophone/src/presentation/qt/config/QtPrivacySettings.cpp" \
           "D:/qutecom-2.2/wengophone/src/presentation/qt/config/QtSecuritySettings.cpp" \
           "D:/qutecom-2.2/wengophone/src/presentation/qt/config/QtVideoSettings.cpp" \
           "D:/qutecom-2.2/wengophone/src/presentation/qt/config/QtVoicemailSettings.cpp" \
           "D:/qutecom-2.2/wengophone/src/presentation/qt/config/QtWengoConfigDialog.cpp" \
           "D:/qutecom-2.2/wengophone/src/presentation/qt/contactlist/ContactGroupPopupMenu.cpp" \
           "D:/qutecom-2.2/wengophone/src/presentation/qt/contactlist/QtConferenceAction.cpp" \
           "D:/qutecom-2.2/wengophone/src/presentation/qt/contactlist/QtContact.cpp" \
           "D:/qutecom-2.2/wengophone/src/presentation/qt/contactlist/QtContactInfo.cpp" \
           "D:/qutecom-2.2/wengophone/src/presentation/qt/contactlist/QtContactList.cpp" \
           "D:/qutecom-2.2/wengophone/src/presentation/qt/contactlist/QtContactListManager.cpp" \
           "D:/qutecom-2.2/wengophone/src/presentation/qt/contactlist/QtContactManager.cpp" \
           "D:/qutecom-2.2/wengophone/src/presentation/qt/contactlist/QtContactMenu.cpp" \
           "D:/qutecom-2.2/wengophone/src/presentation/qt/contactlist/QtContactPixmap.cpp" \
           "D:/qutecom-2.2/wengophone/src/presentation/qt/contactlist/QtContactTreeKeyFilter.cpp" \
           "D:/qutecom-2.2/wengophone/src/presentation/qt/contactlist/QtContactTreeMouseFilter.cpp" \
           "D:/qutecom-2.2/wengophone/src/presentation/qt/contactlist/QtContactWidget.cpp" \
           "D:/qutecom-2.2/wengophone/src/presentation/qt/contactlist/QtRenameGroup.cpp" \
           "D:/qutecom-2.2/wengophone/src/presentation/qt/contactlist/QtTreeViewDelegate.cpp" \
           "D:/qutecom-2.2/wengophone/src/presentation/qt/filetransfer/QtFileTransfer.cpp" \
           "D:/qutecom-2.2/wengophone/src/presentation/qt/filetransfer/QtFileTransferAcceptDialog.cpp" \
           "D:/qutecom-2.2/wengophone/src/presentation/qt/filetransfer/QtFileTransferDownloadItem.cpp" \
           "D:/qutecom-2.2/wengophone/src/presentation/qt/filetransfer/QtFileTransferItem.cpp" \
           "D:/qutecom-2.2/wengophone/src/presentation/qt/filetransfer/QtFileTransferNotifyDialog.cpp" \
           "D:/qutecom-2.2/wengophone/src/presentation/qt/filetransfer/QtFileTransferUploadItem.cpp" \
           "D:/qutecom-2.2/wengophone/src/presentation/qt/filetransfer/QtFileTransferWidget.cpp" \
           "D:/qutecom-2.2/wengophone/src/presentation/qt/history/QtHistory.cpp" \
           "D:/qutecom-2.2/wengophone/src/presentation/qt/history/QtHistoryWidget.cpp" \
           "D:/qutecom-2.2/wengophone/src/presentation/qt/imaccount/QtAIMSettings.cpp" \
           "D:/qutecom-2.2/wengophone/src/presentation/qt/imaccount/QtGoogleTalkSettings.cpp" \
           "D:/qutecom-2.2/wengophone/src/presentation/qt/imaccount/QtICQSettings.cpp" \
           "D:/qutecom-2.2/wengophone/src/presentation/qt/imaccount/QtIMAccountManager.cpp" \
           "D:/qutecom-2.2/wengophone/src/presentation/qt/imaccount/QtIMAccountPlugin.cpp" \
           "D:/qutecom-2.2/wengophone/src/presentation/qt/imaccount/QtIMAccountSettings.cpp" \
           "D:/qutecom-2.2/wengophone/src/presentation/qt/imaccount/QtJabberSettings.cpp" \
           "D:/qutecom-2.2/wengophone/src/presentation/qt/imaccount/QtMSNSettings.cpp" \
           "D:/qutecom-2.2/wengophone/src/presentation/qt/imaccount/QtYahooSettings.cpp" \
           "D:/qutecom-2.2/wengophone/src/presentation/qt/imcontact/QtAddIMContact.cpp" \
           "D:/qutecom-2.2/wengophone/src/presentation/qt/imcontact/QtAdvancedIMContactManager.cpp" \
           "D:/qutecom-2.2/wengophone/src/presentation/qt/imcontact/QtIMContactItem.cpp" \
           "D:/qutecom-2.2/wengophone/src/presentation/qt/imcontact/QtIMContactManagerInterface.cpp" \
           "D:/qutecom-2.2/wengophone/src/presentation/qt/imcontact/QtSimpleIMContactManager.cpp" \
           "D:/qutecom-2.2/wengophone/src/presentation/qt/login/ILogin.cpp" \
           "D:/qutecom-2.2/wengophone/src/presentation/qt/login/QtAddAccount.cpp" \
           "D:/qutecom-2.2/wengophone/src/presentation/qt/login/QtAddAccountUtils.cpp" \
           "D:/qutecom-2.2/wengophone/src/presentation/qt/login/QtAddSIPAccount.cpp" \
           "D:/qutecom-2.2/wengophone/src/presentation/qt/login/QtAddWengoAccount.cpp" \
           "D:/qutecom-2.2/wengophone/src/presentation/qt/login/QtLogAccount.cpp" \
           "D:/qutecom-2.2/wengophone/src/presentation/qt/login/QtLoginDialog.cpp" \
           "D:/qutecom-2.2/wengophone/src/presentation/qt/macosx/QtMacApplication.cpp" \
           "D:/qutecom-2.2/wengophone/src/presentation/qt/phonecall/QtAudioSmileysWindow.cpp" \
           "D:/qutecom-2.2/wengophone/src/presentation/qt/phonecall/QtContactCallListWidget.cpp" \
           "D:/qutecom-2.2/wengophone/src/presentation/qt/phonecall/QtPhoneCall.cpp" \
           "D:/qutecom-2.2/wengophone/src/presentation/qt/phonecall/QtPhoneCallEventFilter.cpp" \
           "D:/qutecom-2.2/wengophone/src/presentation/qt/phonecall/QtVideo.cpp" \
           "D:/qutecom-2.2/wengophone/src/presentation/qt/phonecall/QtVideoQt.cpp" \
           "D:/qutecom-2.2/wengophone/src/presentation/qt/phonecall/QtVideoXV.cpp" \
           "D:/qutecom-2.2/wengophone/src/presentation/qt/phonecall/XVWindow.cpp" \
           "D:/qutecom-2.2/wengophone/src/presentation/qt/phoneline/QtPhoneLine.cpp" \
           "D:/qutecom-2.2/wengophone/src/presentation/qt/profile/QtProfileDetails.cpp" \
           "D:/qutecom-2.2/wengophone/src/presentation/qt/profile/QtUserProfile.cpp" \
           "D:/qutecom-2.2/wengophone/src/presentation/qt/profile/QtUserProfileHandler.cpp" \
           "D:/qutecom-2.2/wengophone/src/presentation/qt/profilebar/QtCreditWidget.cpp" \
           "D:/qutecom-2.2/wengophone/src/presentation/qt/profilebar/QtEventWidget.cpp" \
           "D:/qutecom-2.2/wengophone/src/presentation/qt/profilebar/QtIMAccountPresenceMenuManager.cpp" \
           "D:/qutecom-2.2/wengophone/src/presentation/qt/profilebar/QtIMProfileWidget.cpp" \
           "D:/qutecom-2.2/wengophone/src/presentation/qt/profilebar/QtProfileBar.cpp" \
           "D:/qutecom-2.2/wengophone/src/presentation/qt/statusbar/QtStatusBar.cpp" \
           "D:/qutecom-2.2/wengophone/src/presentation/qt/toaster/QtCallToaster.cpp" \
           "D:/qutecom-2.2/wengophone/src/presentation/qt/toaster/QtChatToaster.cpp" \
           "D:/qutecom-2.2/wengophone/src/presentation/qt/toaster/QtToaster.cpp" \
           "D:/qutecom-2.2/wengophone/src/presentation/qt/webdirectory/QtWebDirectory.cpp" \
           "D:/qutecom-2.2/wengophone/src/presentation/qt/webservices/sms/QtSms.cpp" \
           "D:/qutecom-2.2/wengophone/src/presentation/qt/webservices/softupdate/QtBrowserSoftUpdate.cpp" \
           "D:/qutecom-2.2/wengophone/src/presentation/qt/webservices/softupdate/QtSoftUpdate.cpp" \
           "D:/qutecom-2.2/wengophone/src/presentation/qt/wenbox/QtWenboxPlugin.cpp" \
           "D:/qutecom-2.2/wengophone/src/presentation/xpcom/src/Command.cpp" \
           "D:/qutecom-2.2/wengophone/src/presentation/xpcom/src/XPCOMIMHandler.cpp" \
           "D:/qutecom-2.2/wengophone/src/presentation/xpcom/src/XPCOMPhoneCall.cpp" \
           "D:/qutecom-2.2/wengophone/src/presentation/xpcom/src/XPCOMPhoneLine.cpp" \
           "D:/qutecom-2.2/wengophone/src/presentation/xpcom/src/XPCOMSms.cpp" \
           "D:/qutecom-2.2/wengophone/src/presentation/xpcom/src/XPCOMUserProfile.cpp" \
           "D:/qutecom-2.2/wengophone/src/presentation/xpcom/src/XPCOMWengoPhone.cpp" \
           "D:/qutecom-2.2/wengophone/src/presentation/xpcom/tests/MainWindow.cpp" \
           "D:/qutecom-2.2/wengophone/src/presentation/xpcom/tests/main.cpp" \
           "D:/qutecom-2.2/crashreport/FtpUpload.cpp" \
           "D:/qutecom-2.2/crashreport/QtCrashReport.cpp" \
           "D:/qutecom-2.2/crashreport/main.cpp" \
           "D:/qutecom-2.2/libs/qtutil/src/AnimatedButton.cpp" \
           "D:/qutecom-2.2/libs/qtutil/src/ClearLineEdit.cpp" \
           "D:/qutecom-2.2/libs/qtutil/src/ClickableLabel.cpp" \
           "D:/qutecom-2.2/libs/qtutil/src/CloseEventFilter.cpp" \
           "D:/qutecom-2.2/libs/qtutil/src/DesktopService.cpp" \
           "D:/qutecom-2.2/libs/qtutil/src/DropDownWindow.cpp" \
           "D:/qutecom-2.2/libs/qtutil/src/EnabledChangeEventFilter.cpp" \
           "D:/qutecom-2.2/libs/qtutil/src/EventFilter.cpp" \
           "D:/qutecom-2.2/libs/qtutil/src/ExpandButton.cpp" \
           "D:/qutecom-2.2/libs/qtutil/src/FSResourceFileEngineHandler.cpp" \
           "D:/qutecom-2.2/libs/qtutil/src/IconLineEdit.cpp" \
           "D:/qutecom-2.2/libs/qtutil/src/ImageSelector.cpp" \
           "D:/qutecom-2.2/libs/qtutil/src/KeyEventFilter.cpp" \
           "D:/qutecom-2.2/libs/qtutil/src/KeywordTranslator.cpp" \
           "D:/qutecom-2.2/libs/qtutil/src/LanguageChangeEventFilter.cpp" \
           "D:/qutecom-2.2/libs/qtutil/src/LinkLabel.cpp" \
           "D:/qutecom-2.2/libs/qtutil/src/MacDesktopService.cpp" \
           "D:/qutecom-2.2/libs/qtutil/src/MouseEventFilter.cpp" \
           "D:/qutecom-2.2/libs/qtutil/src/NonResizeableWidget.cpp" \
           "D:/qutecom-2.2/libs/qtutil/src/Object.cpp" \
           "D:/qutecom-2.2/libs/qtutil/src/OsdButton.cpp" \
           "D:/qutecom-2.2/libs/qtutil/src/PaintEventFilter.cpp" \
           "D:/qutecom-2.2/libs/qtutil/src/PixmapMerging.cpp" \
           "D:/qutecom-2.2/libs/qtutil/src/QObjectThreadSafe.cpp" \
           "D:/qutecom-2.2/libs/qtutil/src/QtThumbnailDirModel.cpp" \
           "D:/qutecom-2.2/libs/qtutil/src/QtThumbnailManager.cpp" \
           "D:/qutecom-2.2/libs/qtutil/src/ResizeEventFilter.cpp" \
           "D:/qutecom-2.2/libs/qtutil/src/SafeConnect.cpp" \
           "D:/qutecom-2.2/libs/qtutil/src/ScrollFrame.cpp" \
           "D:/qutecom-2.2/libs/qtutil/src/StringListConvert.cpp" \
           "D:/qutecom-2.2/libs/qtutil/src/ThreadEventFilter.cpp" \
           "D:/qutecom-2.2/libs/qtutil/src/ThumbnailView.cpp" \
           "D:/qutecom-2.2/libs/qtutil/src/ToolTipLineEdit.cpp" \
           "D:/qutecom-2.2/libs/qtutil/src/UpQComboBox.cpp" \
           "D:/qutecom-2.2/libs/qtutil/src/WengoStyleLabel.cpp" \
           "D:/qutecom-2.2/libs/qtutil/src/Widget.cpp" \
           "D:/qutecom-2.2/libs/qtutil/src/WidgetBackgroundImage.cpp" \
           "D:/qutecom-2.2/libs/qtutil/src/WidgetFactory.cpp" \
           "D:/qutecom-2.2/libs/qtutil/src/WidgetRatioEnforcer.cpp" \
           "D:/qutecom-2.2/libs/qtutil/src/WidgetUtils.cpp" \
           "D:/qutecom-2.2/libs/qtutil/src/WindowsDesktopService.cpp" \
           "D:/qutecom-2.2/libs/qtutil/src/Wizard.cpp" \
           "D:/qutecom-2.2/libs/qtutil/tests/desktopservice.cpp" \
           "D:/qutecom-2.2/libs/qtutil/tests/main.cpp" \
           "D:/qutecom-2.2/libs/qtutil/tests/testdropdownwindow.cpp" \
           "D:/qutecom-2.2/libs/qtutil/tests/testexpandbutton.cpp" \
           "D:/qutecom-2.2/libs/qtutil/tests/testflashwindow.cpp" \
           "D:/qutecom-2.2/libs/qtutil/tests/testimageselector.cpp" \
           "D:/qutecom-2.2/libs/qtutil/tests/testlineedit.cpp" \
           "D:/qutecom-2.2/libs/qtutil/tests/testlinklabel.cpp" \
           "D:/qutecom-2.2/libs/qtutil/tests/testqobjectthreadsafe.cpp" \
           "D:/qutecom-2.2/libs/qtutil/tests/testscrollframe.cpp" \
           "D:/qutecom-2.2/libs/qtutil/tests/testwidgetratioenforcer.cpp" \
           "D:/qutecom-2.2/libs/owbrowser/src/QtBrowser.cpp" \


FORMS += \
         "D:/qutecom-2.2/wengophone/src/presentation/qt/AboutWindow.ui" \
         "D:/qutecom-2.2/wengophone/src/presentation/qt/DialpadWidget.ui" \
         "D:/qutecom-2.2/wengophone/src/presentation/qt/HttpProxyLoginWindow.ui" \
         "D:/qutecom-2.2/wengophone/src/presentation/qt/NoWengoAlert.ui" \
         "D:/qutecom-2.2/wengophone/src/presentation/qt/WengoPhoneWindow.ui" \
         "D:/qutecom-2.2/wengophone/src/presentation/qt/chat/AvatarFrame.ui" \
         "D:/qutecom-2.2/wengophone/src/presentation/qt/chat/AvatarWidget.ui" \
         "D:/qutecom-2.2/wengophone/src/presentation/qt/chat/ChatLogViewer.ui" \
         "D:/qutecom-2.2/wengophone/src/presentation/qt/chat/ChatMainWindow.ui" \
         "D:/qutecom-2.2/wengophone/src/presentation/qt/chat/ChatWidget.ui" \
         "D:/qutecom-2.2/wengophone/src/presentation/qt/chat/UserFrame.ui" \
         "D:/qutecom-2.2/wengophone/src/presentation/qt/chat/chatroom/ChatRoomInviteWidget.ui" \
         "D:/qutecom-2.2/wengophone/src/presentation/qt/conference/ConferenceCallWidget.ui" \
         "D:/qutecom-2.2/wengophone/src/presentation/qt/conference/ConferenceInviteWidget.ui" \
         "D:/qutecom-2.2/wengophone/src/presentation/qt/config/AccountSettings.ui" \
         "D:/qutecom-2.2/wengophone/src/presentation/qt/config/AdvancedConfigWindow.ui" \
         "D:/qutecom-2.2/wengophone/src/presentation/qt/config/AdvancedSettings.ui" \
         "D:/qutecom-2.2/wengophone/src/presentation/qt/config/AppearanceSettings.ui" \
         "D:/qutecom-2.2/wengophone/src/presentation/qt/config/AudioSettings.ui" \
         "D:/qutecom-2.2/wengophone/src/presentation/qt/config/CallForwardSettings.ui" \
         "D:/qutecom-2.2/wengophone/src/presentation/qt/config/GeneralSettings.ui" \
         "D:/qutecom-2.2/wengophone/src/presentation/qt/config/LanguagesSettings.ui" \
         "D:/qutecom-2.2/wengophone/src/presentation/qt/config/ManageBlockedUsersSettings.ui" \
         "D:/qutecom-2.2/wengophone/src/presentation/qt/config/NotificationSettings.ui" \
         "D:/qutecom-2.2/wengophone/src/presentation/qt/config/NotificationSettingsItem.ui" \
         "D:/qutecom-2.2/wengophone/src/presentation/qt/config/PrivacySettings.ui" \
         "D:/qutecom-2.2/wengophone/src/presentation/qt/config/SecuritySettings.ui" \
         "D:/qutecom-2.2/wengophone/src/presentation/qt/config/VideoSettings.ui" \
         "D:/qutecom-2.2/wengophone/src/presentation/qt/config/VoicemailSettings.ui" \
         "D:/qutecom-2.2/wengophone/src/presentation/qt/config/WengoConfigDialog.ui" \
         "D:/qutecom-2.2/wengophone/src/presentation/qt/contactlist/ContactList.ui" \
         "D:/qutecom-2.2/wengophone/src/presentation/qt/contactlist/ContactWidget.ui" \
         "D:/qutecom-2.2/wengophone/src/presentation/qt/contactlist/RenameGroupDialog.ui" \
         "D:/qutecom-2.2/wengophone/src/presentation/qt/filetransfer/AcceptDialog.ui" \
         "D:/qutecom-2.2/wengophone/src/presentation/qt/filetransfer/FileTransferDialog.ui" \
         "D:/qutecom-2.2/wengophone/src/presentation/qt/filetransfer/FileTransferItem.ui" \
         "D:/qutecom-2.2/wengophone/src/presentation/qt/filetransfer/NotifyDialog.ui" \
         "D:/qutecom-2.2/wengophone/src/presentation/qt/history/HistoryWidget.ui" \
         "D:/qutecom-2.2/wengophone/src/presentation/qt/imaccount/AIMSettings.ui" \
         "D:/qutecom-2.2/wengophone/src/presentation/qt/imaccount/GoogleTalkSettings.ui" \
         "D:/qutecom-2.2/wengophone/src/presentation/qt/imaccount/ICQSettings.ui" \
         "D:/qutecom-2.2/wengophone/src/presentation/qt/imaccount/IMAccountManager.ui" \
         "D:/qutecom-2.2/wengophone/src/presentation/qt/imaccount/IMAccountTemplate.ui" \
         "D:/qutecom-2.2/wengophone/src/presentation/qt/imaccount/JabberSettings.ui" \
         "D:/qutecom-2.2/wengophone/src/presentation/qt/imaccount/MSNSettings.ui" \
         "D:/qutecom-2.2/wengophone/src/presentation/qt/imaccount/YahooSettings.ui" \
         "D:/qutecom-2.2/wengophone/src/presentation/qt/imcontact/AddIMContact.ui" \
         "D:/qutecom-2.2/wengophone/src/presentation/qt/imcontact/IMContactManager.ui" \
         "D:/qutecom-2.2/wengophone/src/presentation/qt/imcontact/SimpleIMContactManager.ui" \
         "D:/qutecom-2.2/wengophone/src/presentation/qt/login/AddAccount.ui" \
         "D:/qutecom-2.2/wengophone/src/presentation/qt/login/AddSIPAccount.ui" \
         "D:/qutecom-2.2/wengophone/src/presentation/qt/login/AddWengoAccount.ui" \
         "D:/qutecom-2.2/wengophone/src/presentation/qt/login/LogAccount.ui" \
         "D:/qutecom-2.2/wengophone/src/presentation/qt/phonecall/PhoneCallWidget.ui" \
         "D:/qutecom-2.2/wengophone/src/presentation/qt/phonecall/VideoWindow.ui" \
         "D:/qutecom-2.2/wengophone/src/presentation/qt/profile/ProfileDetails.ui" \
         "D:/qutecom-2.2/wengophone/src/presentation/qt/profilebar/CreditWidget.ui" \
         "D:/qutecom-2.2/wengophone/src/presentation/qt/profilebar/EventWidget.ui" \
         "D:/qutecom-2.2/wengophone/src/presentation/qt/profilebar/IMProfileWidget.ui" \
         "D:/qutecom-2.2/wengophone/src/presentation/qt/statusbar/StatusBarWidget.ui" \
         "D:/qutecom-2.2/wengophone/src/presentation/qt/toaster/QtCallToaster.ui" \
         "D:/qutecom-2.2/wengophone/src/presentation/qt/toaster/QtChatToaster.ui" \
         "D:/qutecom-2.2/wengophone/src/presentation/qt/webservices/sms/SmsWindow.ui" \
         "D:/qutecom-2.2/wengophone/src/presentation/qt/webservices/softupdate/BrowserSoftUpdateWindow.ui" \
         "D:/qutecom-2.2/wengophone/src/presentation/qt/webservices/softupdate/SoftUpdateWindow.ui" \
         "D:/qutecom-2.2/wengophone/src/presentation/xpcom/tests/MainWindow.ui" \
         "D:/qutecom-2.2/crashreport/CrashReport.ui" \
         "D:/qutecom-2.2/libs/qtutil/src/ImageSelector.ui" \
         "D:/qutecom-2.2/libs/qtutil/src/Wizard.ui" \


TRANSLATIONS += \
                "D:/qutecom-2.2/wengophone/src/presentation/qt/lang/qtwengophone_bg.ts" \
                "D:/qutecom-2.2/wengophone/src/presentation/qt/lang/qtwengophone_ca.ts" \
                "D:/qutecom-2.2/wengophone/src/presentation/qt/lang/qtwengophone_cs.ts" \
                "D:/qutecom-2.2/wengophone/src/presentation/qt/lang/qtwengophone_cy.ts" \
                "D:/qutecom-2.2/wengophone/src/presentation/qt/lang/qtwengophone_da.ts" \
                "D:/qutecom-2.2/wengophone/src/presentation/qt/lang/qtwengophone_de.ts" \
                "D:/qutecom-2.2/wengophone/src/presentation/qt/lang/qtwengophone_el.ts" \
                "D:/qutecom-2.2/wengophone/src/presentation/qt/lang/qtwengophone_en.ts" \
                "D:/qutecom-2.2/wengophone/src/presentation/qt/lang/qtwengophone_en_GB.ts" \
                "D:/qutecom-2.2/wengophone/src/presentation/qt/lang/qtwengophone_eo.ts" \
                "D:/qutecom-2.2/wengophone/src/presentation/qt/lang/qtwengophone_es.ts" \
                "D:/qutecom-2.2/wengophone/src/presentation/qt/lang/qtwengophone_fi.ts" \
                "D:/qutecom-2.2/wengophone/src/presentation/qt/lang/qtwengophone_fr.ts" \
                "D:/qutecom-2.2/wengophone/src/presentation/qt/lang/qtwengophone_gl.ts" \
                "D:/qutecom-2.2/wengophone/src/presentation/qt/lang/qtwengophone_he.ts" \
                "D:/qutecom-2.2/wengophone/src/presentation/qt/lang/qtwengophone_hi.ts" \
                "D:/qutecom-2.2/wengophone/src/presentation/qt/lang/qtwengophone_hu.ts" \
                "D:/qutecom-2.2/wengophone/src/presentation/qt/lang/qtwengophone_it.ts" \
                "D:/qutecom-2.2/wengophone/src/presentation/qt/lang/qtwengophone_ja.ts" \
                "D:/qutecom-2.2/wengophone/src/presentation/qt/lang/qtwengophone_ku.ts" \
                "D:/qutecom-2.2/wengophone/src/presentation/qt/lang/qtwengophone_lv.ts" \
                "D:/qutecom-2.2/wengophone/src/presentation/qt/lang/qtwengophone_mn.ts" \
                "D:/qutecom-2.2/wengophone/src/presentation/qt/lang/qtwengophone_nb.ts" \
                "D:/qutecom-2.2/wengophone/src/presentation/qt/lang/qtwengophone_nl.ts" \
                "D:/qutecom-2.2/wengophone/src/presentation/qt/lang/qtwengophone_pl.ts" \
                "D:/qutecom-2.2/wengophone/src/presentation/qt/lang/qtwengophone_pt.ts" \
                "D:/qutecom-2.2/wengophone/src/presentation/qt/lang/qtwengophone_pt_BR.ts" \
                "D:/qutecom-2.2/wengophone/src/presentation/qt/lang/qtwengophone_ro.ts" \
                "D:/qutecom-2.2/wengophone/src/presentation/qt/lang/qtwengophone_ru.ts" \
                "D:/qutecom-2.2/wengophone/src/presentation/qt/lang/qtwengophone_sk.ts" \
                "D:/qutecom-2.2/wengophone/src/presentation/qt/lang/qtwengophone_sl.ts" \
                "D:/qutecom-2.2/wengophone/src/presentation/qt/lang/qtwengophone_sr.ts" \
                "D:/qutecom-2.2/wengophone/src/presentation/qt/lang/qtwengophone_sv.ts" \
                "D:/qutecom-2.2/wengophone/src/presentation/qt/lang/qtwengophone_tr.ts" \
                "D:/qutecom-2.2/wengophone/src/presentation/qt/lang/qtwengophone_uz.ts" \
                "D:/qutecom-2.2/wengophone/src/presentation/qt/lang/qtwengophone_vi.ts" \
                "D:/qutecom-2.2/wengophone/src/presentation/qt/lang/qtwengophone_zh.ts" \
                "D:/qutecom-2.2/wengophone/src/presentation/qt/lang/qtwengophone_zh_CN.ts" \
                "D:/qutecom-2.2/wengophone/src/presentation/qt/lang/qtwengophone_zh_HK.ts" \
                "D:/qutecom-2.2/libs/qtutil/tests/fallback.ts" \
                "D:/qutecom-2.2/libs/qtutil/tests/test.ts" \


