/*
 * This file was generated by qdbusxml2cpp version 0.7
 * Command line was: qdbusxml2cpp -c KinectAdaptor -a KinectAdaptor.h:KinectAdaptor.cpp .\com.dcampus.coolview.kinect.xml
 *
 * qdbusxml2cpp is Copyright (C) 2010 Nokia Corporation and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef KINECTADAPTOR_H_1313637314
#define KINECTADAPTOR_H_1313637314

#include <QtCore/QObject>
#include <QtDBus/QtDBus>
class QByteArray;
template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;
class QStringList;
class QVariant;

/*
 * Adaptor class for interface com.dcampus.coolview.kinect
 */
class KinectAdaptor: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "com.dcampus.coolview.kinect")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"com.dcampus.coolview.kinect\">\n"
"    <signal name=\"GestureOccur\">\n"
"      <arg direction=\"out\" type=\"s\" name=\"to\"/>\n"
"      <arg direction=\"out\" type=\"i\" name=\"type\"/>\n"
"    </signal>\n"
"    <signal name=\"KinectMessage\">\n"
"      <arg direction=\"out\" type=\"i\" name=\"type\"/>\n"
"      <arg direction=\"out\" type=\"s\" name=\"message\"/>\n"
"    </signal>\n"
"  </interface>\n"
        "")
public:
    KinectAdaptor(QObject *parent);
    virtual ~KinectAdaptor();

public: // PROPERTIES
public Q_SLOTS: // METHODS
Q_SIGNALS: // SIGNALS
    void GestureOccur(const QString &to, int type);
    void KinectMessage(int type, const QString &message);
};

#endif
